/**
 * build-weather.mjs — generates src/weatherData.js: Eorzean weather tables
 * for every zone our catalogs reference.
 *
 * Source: Garland Tools core data (skywatcher.weatherRateIndex — cumulative
 * percentage thresholds per weather, exactly what the in-game forecast
 * algorithm consumes — plus locationIndex name → weatherRate).
 *
 * Run after adding zones/spots:  node backend/build-weather.mjs
 */
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import { MINING_NODES } from '../src/miningData.js'
import { BOTANY_NODES } from '../src/botanyData.js'
import { FISHING_SPOTS } from '../src/fishingData.js'

const here = path.dirname(fileURLToPath(import.meta.url))

const zones = new Set()
for (const n of [...MINING_NODES, ...BOTANY_NODES]) zones.add(n.zone)
for (const s of FISHING_SPOTS) zones.add(s.zone)

const core = await (await fetch('https://www.garlandtools.org/db/doc/core/en/3/data.json')).json()
const { weatherIndex, weatherRateIndex } = core.skywatcher
const byName = new Map(Object.values(core.locationIndex).map((l) => [l.name, l]))

const out = {}
const missing = []
for (const zone of [...zones].sort()) {
  const loc = byName.get(zone)
  const rate = loc?.weatherRate != null ? weatherRateIndex[loc.weatherRate] : null
  if (!rate) { missing.push(zone); continue }
  // rates are cumulative upper bounds in order: chance < rate ⇒ that weather.
  out[zone] = rate.rates.map((r) => [r.rate, weatherIndex[r.weather]])
}

const js = `/* Auto-generated by backend/build-weather.mjs — DO NOT EDIT BY HAND.
   Per-zone Eorzean weather tables: ordered [cumulativeThreshold, weatherName]
   pairs consumed by src/eorzeaWeather.js (chance < threshold ⇒ that weather).
   Source: Garland Tools skywatcher data. */

export const ZONE_WEATHER = ${JSON.stringify(out, null, 2)}
`
fs.writeFileSync(path.join(here, '..', 'src', 'weatherData.js'), js)
console.log(`wrote src/weatherData.js: ${Object.keys(out).length} zones`)
if (missing.length) console.log('no weather table (instances/sub-areas — fine):', missing.join(', '))
