/**
 * scrape-bait.js — Fishing Tackle (bait/lure) reference with vendor info.
 *
 * Source: FFXIV Teamcraft. Enumerates every item in UI category 33
 * (Fishing Tackle) and resolves the cheapest NPC gil-shop vendor for each
 * (seller name + zone + map coords + price).
 *
 * Output: src/baitTackleData.js  (export const BAIT_TACKLE = [...])
 * Run:    node backend/scrape-bait.js
 */
const fs = require('fs');
const path = require('path');

const BASE = 'https://raw.githubusercontent.com/ffxiv-teamcraft/ffxiv-teamcraft/master/libs/data/src/lib/json/';
const TACKLE_CATEGORY = 33;
const getJson = async (f) => {
  const r = await fetch(BASE + f);
  if (!r.ok) throw new Error(`${f}: HTTP ${r.status}`);
  return r.json();
};
const coordStr = (x, y) => `X:${Number(x).toFixed(1)}, Y:${Number(y).toFixed(1)}`;

async function main() {
  console.log('Fetching Teamcraft data…');
  const [items, ui, shops, npcs, places] = await Promise.all([
    getJson('items.json'),
    getJson('ui-categories.json'),
    getJson('shops.json'),
    getJson('npcs.json'),
    getJson('places.json'),
  ]);

  // Cheapest gil-shop vendor per item.
  const vmap = new Map();
  for (const shop of Object.values(shops)) {
    if (shop.type !== 'GilShop') continue;
    const npcId = (shop.npcs || [])[0];
    for (const t of (shop.trades || [])) {
      const gil = (t.currencies || []).find((c) => c.id === 1);
      if (!gil) continue;
      for (const it of (t.items || [])) {
        const prev = vmap.get(it.id);
        if (!prev || gil.amount < prev.price) vmap.set(it.id, { price: gil.amount, npcId });
      }
    }
  }

  const tackleIds = Object.entries(ui).filter(([, c]) => c === TACKLE_CATEGORY).map(([id]) => Number(id));
  const out = tackleIds
    .map((id) => {
      const name = items[id]?.en;
      if (!name) return null;
      const v = vmap.get(id);
      let vendor = null;
      if (v) {
        const npc = npcs[v.npcId];
        const pos = npc?.position;
        vendor = {
          npc: npc?.en || 'Vendor',
          zone: pos ? (places[pos.zoneid]?.en || null) : null,
          coords: pos && pos.x != null ? coordStr(pos.x, pos.y) : null,
          price: v.price,
        };
      }
      return { name, vendor };
    })
    .filter(Boolean)
    .sort((a, b) => {
      // Vendor-buyable first (cheapest), then the rest alphabetically.
      if (!!a.vendor !== !!b.vendor) return a.vendor ? -1 : 1;
      if (a.vendor && b.vendor) return a.vendor.price - b.vendor.price || a.name.localeCompare(b.name);
      return a.name.localeCompare(b.name);
    });

  const withV = out.filter((b) => b.vendor).length;
  console.log(`Fishing Tackle items: ${out.length} (with gil vendor: ${withV})`);

  const dest = path.join(__dirname, '..', 'src', 'baitTackleData.js');
  const body =
    '/* Generated by backend/scrape-bait.js from FFXIV Teamcraft (UI category 33,\n' +
    '   Fishing Tackle). Each entry: { name, vendor: { npc, zone, coords, price } | null }.\n' +
    '   Re-run the scraper to refresh. */\n' +
    'export const BAIT_TACKLE = ' + JSON.stringify(out) + '\n';
  fs.writeFileSync(dest, body, 'utf8');
  console.log(`Wrote ${dest}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
