require('dotenv').config();
const { Pool } = require('pg');

const pool = new Pool({
  connectionString: process.env.DATABASE_PUBLIC_URL || process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false },
});

// Canonical seed: the 30 real Dawntrail hunt marks (2 B + 2 A + 1 S per zone),
// verified vs consolegameswiki + Destructoid. Enriched with spawn data:
// B-ranks roam the zone (no fixed spawn); A-ranks roam set spawn-point pools;
// S-ranks are weekly conditional spawns (the trigger is in tips).
const sql = `
INSERT INTO hunts (id, name, rank, type, bill_number, zone, area, coords, coords_note, targets, reward, authority, tips, status) VALUES
(116, 'Go''ozoabek''be', 'B', 'Beginner Dawn Hunt', 'Daily', 'Kozama''uka', 'Kozama''uka', NULL, 'Roams Kozama''uka — no fixed spawn', 1, '10 Sacks of Nuts · 1,000 Gil', 'Dawn Hunt', ARRAY['B-rank Wanted mark on the daily Beginner Dawn Hunt bill.', 'B-ranks wander the whole zone with no spawn timer — patrol Kozama''uka to find it.'], 'todo'),
(117, 'The Slammer', 'B', 'Beginner Dawn Hunt', 'Daily', 'Kozama''uka', 'Kozama''uka', NULL, 'Roams Kozama''uka — no fixed spawn', 1, '10 Sacks of Nuts · 1,000 Gil', 'Dawn Hunt', ARRAY['B-rank Wanted mark on the daily Beginner Dawn Hunt bill.', 'B-ranks wander the whole zone with no spawn timer — patrol Kozama''uka to find it.'], 'todo'),
(118, 'Chupacabra', 'B', 'Beginner Dawn Hunt', 'Daily', 'Urqopacha', 'Urqopacha', NULL, 'Roams Urqopacha — no fixed spawn', 1, '10 Sacks of Nuts · 1,000 Gil', 'Dawn Hunt', ARRAY['B-rank Wanted mark on the daily Beginner Dawn Hunt bill.', 'B-ranks wander the whole zone with no spawn timer — patrol Urqopacha to find it.'], 'todo'),
(119, 'Mad Maguey', 'B', 'Beginner Dawn Hunt', 'Daily', 'Urqopacha', 'Urqopacha', NULL, 'Roams Urqopacha — no fixed spawn', 1, '10 Sacks of Nuts · 1,000 Gil', 'Dawn Hunt', ARRAY['B-rank Wanted mark on the daily Beginner Dawn Hunt bill.', 'B-ranks wander the whole zone with no spawn timer — patrol Urqopacha to find it.'], 'todo'),
(120, 'Leafscourge Hadoll Ja', 'B', 'Intermediate Dawn Hunt', 'Daily', 'Yak T''el', 'Yak T''el', NULL, 'Roams Yak T''el — no fixed spawn', 1, '10 Sacks of Nuts · 1,000 Gil', 'Dawn Hunt', ARRAY['B-rank Wanted mark on the daily Intermediate Dawn Hunt bill.', 'B-ranks wander the whole zone with no spawn timer — patrol Yak T''el to find it.'], 'todo'),
(121, 'Xty''iinbek', 'B', 'Intermediate Dawn Hunt', 'Daily', 'Yak T''el', 'Yak T''el', NULL, 'Roams Yak T''el — no fixed spawn', 1, '10 Sacks of Nuts · 1,000 Gil', 'Dawn Hunt', ARRAY['B-rank Wanted mark on the daily Intermediate Dawn Hunt bill.', 'B-ranks wander the whole zone with no spawn timer — patrol Yak T''el to find it.'], 'todo'),
(122, 'Nopalitender Fabuloso', 'B', 'Intermediate Dawn Hunt', 'Daily', 'Shaaloani', 'Shaaloani', NULL, 'Roams Shaaloani — no fixed spawn', 1, '10 Sacks of Nuts · 1,000 Gil', 'Dawn Hunt', ARRAY['B-rank Wanted mark on the daily Intermediate Dawn Hunt bill.', 'B-ranks wander the whole zone with no spawn timer — patrol Shaaloani to find it.'], 'todo'),
(123, 'Uktena', 'B', 'Intermediate Dawn Hunt', 'Daily', 'Shaaloani', 'Shaaloani', NULL, 'Roams Shaaloani — no fixed spawn', 1, '10 Sacks of Nuts · 1,000 Gil', 'Dawn Hunt', ARRAY['B-rank Wanted mark on the daily Intermediate Dawn Hunt bill.', 'B-ranks wander the whole zone with no spawn timer — patrol Shaaloani to find it.'], 'todo'),
(124, 'Gallowsbeak', 'B', 'Intermediate Dawn Hunt', 'Daily', 'Heritage Found', 'Heritage Found', NULL, 'Roams Heritage Found — no fixed spawn', 1, '10 Sacks of Nuts · 1,000 Gil', 'Dawn Hunt', ARRAY['B-rank Wanted mark on the daily Intermediate Dawn Hunt bill.', 'B-ranks wander the whole zone with no spawn timer — patrol Heritage Found to find it.'], 'todo'),
(125, 'Gargant', 'B', 'Intermediate Dawn Hunt', 'Daily', 'Heritage Found', 'Heritage Found', NULL, 'Roams Heritage Found — no fixed spawn', 1, '10 Sacks of Nuts · 1,000 Gil', 'Dawn Hunt', ARRAY['B-rank Wanted mark on the daily Intermediate Dawn Hunt bill.', 'B-ranks wander the whole zone with no spawn timer — patrol Heritage Found to find it.'], 'todo'),
(126, '13th Child', 'B', 'Intermediate Dawn Hunt', 'Daily', 'Living Memory', 'Living Memory', NULL, 'Roams Living Memory — no fixed spawn', 1, '10 Sacks of Nuts · 1,000 Gil', 'Dawn Hunt', ARRAY['B-rank Wanted mark on the daily Intermediate Dawn Hunt bill.', 'B-ranks wander the whole zone with no spawn timer — patrol Living Memory to find it.'], 'todo'),
(127, 'Jewel Bearer', 'B', 'Intermediate Dawn Hunt', 'Daily', 'Living Memory', 'Living Memory', NULL, 'Roams Living Memory — no fixed spawn', 1, '10 Sacks of Nuts · 1,000 Gil', 'Dawn Hunt', ARRAY['B-rank Wanted mark on the daily Intermediate Dawn Hunt bill.', 'B-ranks wander the whole zone with no spawn timer — patrol Living Memory to find it.'], 'todo'),
(128, 'Pkuucha', 'A', 'Advanced Dawn Hunt', 'Daily', 'Kozama''uka', 'Kozama''uka', 'X:15.7, Y:16.4', 'Roams Kozama''uka — set spawn points', 1, '40 Sacks of Nuts · 1,500 Gil', 'Dawn Hunt', ARRAY['A-rank Notorious mark on the daily Advanced Dawn Hunt bill.', 'Roams between set spawn points: X:15.7, Y:16.4 · X:19.8, Y:29.1 · X:28.3, Y:17.5.', 'Respawns a few minutes after a kill; use Faloop or a hunt Discord for live status.'], 'todo'),
(129, 'The Raintriller', 'A', 'Advanced Dawn Hunt', 'Daily', 'Kozama''uka', 'Kozama''uka', 'X:15.7, Y:16.4', 'Roams Kozama''uka — set spawn points', 1, '40 Sacks of Nuts · 1,500 Gil', 'Dawn Hunt', ARRAY['A-rank Notorious mark on the daily Advanced Dawn Hunt bill.', 'Roams between set spawn points: X:15.7, Y:16.4 · X:19.8, Y:29.1 · X:28.3, Y:17.5.', 'Respawns a few minutes after a kill; use Faloop or a hunt Discord for live status.'], 'todo'),
(130, 'Nechuciho', 'A', 'Advanced Dawn Hunt', 'Daily', 'Urqopacha', 'Urqopacha', 'X:11.5, Y:9.3', 'Roams Urqopacha — set spawn points', 1, '40 Sacks of Nuts · 1,500 Gil', 'Dawn Hunt', ARRAY['A-rank Notorious mark on the daily Advanced Dawn Hunt bill.', 'Roams between set spawn points: X:11.5, Y:9.3 · X:22.1, Y:20.2 · X:28.1, Y:22.4.', 'Respawns a few minutes after a kill; use Faloop or a hunt Discord for live status.'], 'todo'),
(131, 'Queen Hawk', 'A', 'Advanced Dawn Hunt', 'Daily', 'Urqopacha', 'Urqopacha', 'X:11.5, Y:9.3', 'Roams Urqopacha — set spawn points', 1, '40 Sacks of Nuts · 1,500 Gil', 'Dawn Hunt', ARRAY['A-rank Notorious mark on the daily Advanced Dawn Hunt bill.', 'Roams between set spawn points: X:11.5, Y:9.3 · X:22.1, Y:20.2 · X:28.1, Y:22.4.', 'Respawns a few minutes after a kill; use Faloop or a hunt Discord for live status.'], 'todo'),
(132, 'Rrax Yity''a', 'A', 'Advanced Dawn Hunt', 'Daily', 'Yak T''el', 'Yak T''el', 'X:8.9, Y:19.4', 'Roams Yak T''el — set spawn points', 1, '40 Sacks of Nuts · 1,500 Gil', 'Dawn Hunt', ARRAY['A-rank Notorious mark on the daily Advanced Dawn Hunt bill.', 'Roams between set spawn points: X:8.9, Y:19.4 · X:22.1, Y:28.6 · X:29.9, Y:13.8.', 'Respawns a few minutes after a kill; use Faloop or a hunt Discord for live status.'], 'todo'),
(133, 'Starcrier', 'A', 'Advanced Dawn Hunt', 'Daily', 'Yak T''el', 'Yak T''el', 'X:8.9, Y:19.4', 'Roams Yak T''el — set spawn points', 1, '40 Sacks of Nuts · 1,500 Gil', 'Dawn Hunt', ARRAY['A-rank Notorious mark on the daily Advanced Dawn Hunt bill.', 'Roams between set spawn points: X:8.9, Y:19.4 · X:22.1, Y:28.6 · X:29.9, Y:13.8.', 'Respawns a few minutes after a kill; use Faloop or a hunt Discord for live status.'], 'todo'),
(134, 'Keheniheyamewi', 'A', 'Advanced Dawn Hunt', 'Daily', 'Shaaloani', 'Shaaloani', 'X:9.4, Y:16.4', 'Roams Shaaloani — set spawn points', 1, '40 Sacks of Nuts · 1,500 Gil', 'Dawn Hunt', ARRAY['A-rank Notorious mark on the daily Advanced Dawn Hunt bill.', 'Roams between set spawn points: X:9.4, Y:16.4 · X:23.0, Y:19.2 · X:30.3, Y:22.9.', 'Respawns a few minutes after a kill; use Faloop or a hunt Discord for live status.'], 'todo'),
(135, 'Yehehetoaua''pyo', 'A', 'Advanced Dawn Hunt', 'Daily', 'Shaaloani', 'Shaaloani', 'X:9.4, Y:16.4', 'Roams Shaaloani — set spawn points', 1, '40 Sacks of Nuts · 1,500 Gil', 'Dawn Hunt', ARRAY['A-rank Notorious mark on the daily Advanced Dawn Hunt bill.', 'Roams between set spawn points: X:9.4, Y:16.4 · X:23.0, Y:19.2 · X:30.3, Y:22.9.', 'Respawns a few minutes after a kill; use Faloop or a hunt Discord for live status.'], 'todo'),
(136, 'Heshuala', 'A', 'Advanced Dawn Hunt', 'Daily', 'Heritage Found', 'Heritage Found', 'X:26.6, Y:13.7', 'Roams Heritage Found — set spawn points', 1, '40 Sacks of Nuts · 1,500 Gil', 'Dawn Hunt', ARRAY['A-rank Notorious mark on the daily Advanced Dawn Hunt bill.', 'Roams between set spawn points: X:26.6, Y:13.7 · X:23.8, Y:20.0 · X:14.1, Y:25.5.', 'Respawns a few minutes after a kill; use Faloop or a hunt Discord for live status.'], 'todo'),
(137, 'Urna Variabilis', 'A', 'Advanced Dawn Hunt', 'Daily', 'Heritage Found', 'Heritage Found', 'X:26.6, Y:13.7', 'Roams Heritage Found — set spawn points', 1, '40 Sacks of Nuts · 1,500 Gil', 'Dawn Hunt', ARRAY['A-rank Notorious mark on the daily Advanced Dawn Hunt bill.', 'Roams between set spawn points: X:26.6, Y:13.7 · X:23.8, Y:20.0 · X:14.1, Y:25.5.', 'Respawns a few minutes after a kill; use Faloop or a hunt Discord for live status.'], 'todo'),
(138, 'Cat''s Eye', 'A', 'Advanced Dawn Hunt', 'Daily', 'Living Memory', 'Living Memory', 'X:18.4, Y:19.7', 'Roams Living Memory — set spawn points', 1, '40 Sacks of Nuts · 1,500 Gil', 'Dawn Hunt', ARRAY['A-rank Notorious mark on the daily Advanced Dawn Hunt bill.', 'Roams between set spawn points: X:18.4, Y:19.7 · X:12.7, Y:28.0 · X:26.8, Y:31.2.', 'Respawns a few minutes after a kill; use Faloop or a hunt Discord for live status.'], 'todo'),
(139, 'Sally the Sweeper', 'A', 'Advanced Dawn Hunt', 'Daily', 'Living Memory', 'Living Memory', 'X:18.4, Y:19.7', 'Roams Living Memory — set spawn points', 1, '40 Sacks of Nuts · 1,500 Gil', 'Dawn Hunt', ARRAY['A-rank Notorious mark on the daily Advanced Dawn Hunt bill.', 'Roams between set spawn points: X:18.4, Y:19.7 · X:12.7, Y:28.0 · X:26.8, Y:31.2.', 'Respawns a few minutes after a kill; use Faloop or a hunt Discord for live status.'], 'todo'),
(140, 'Ihnuxokiy', 'S', 'Elite Dawn Hunt', 'Weekly', 'Kozama''uka', 'Kozama''uka', NULL, 'Weekly Elite mark — conditional spawn', 1, '100 Sacks of Nuts · 5,000 Gil', 'Dawn Hunt', ARRAY['Summon the Morpho minion (drops from Lost City of Amdapor HM) and fly low over its spawn points.', 'Weekly Elite Dawn Hunt — coordinate via Faloop / a hunt Discord for the spawn.'], 'todo'),
(141, 'Kirlirger the Abhorrent', 'S', 'Elite Dawn Hunt', 'Weekly', 'Urqopacha', 'Urqopacha', NULL, 'Weekly Elite mark — conditional spawn', 1, '100 Sacks of Nuts · 5,000 Gil', 'Dawn Hunt', ARRAY['Spawns at midnight ET on a foggy night during a new moon.', 'Weekly Elite Dawn Hunt — coordinate via Faloop / a hunt Discord for the spawn.'], 'todo'),
(142, 'Neyoozoteel', 'S', 'Elite Dawn Hunt', 'Weekly', 'Yak T''el', 'Yak T''el', 'X:22.8, Y:35.9', 'Weekly Elite mark — conditional spawn', 1, '100 Sacks of Nuts · 5,000 Gil', 'Dawn Hunt', ARRAY['Discard a stack of 50 or more Fish Meal near a spawn point.', 'Weekly Elite Dawn Hunt — coordinate via Faloop / a hunt Discord for the spawn.'], 'todo'),
(143, 'Sansheya', 'S', 'Elite Dawn Hunt', 'Weekly', 'Shaaloani', 'Shaaloani', 'X:33.9, Y:6.5', 'Weekly Elite mark — conditional spawn', 1, '100 Sacks of Nuts · 5,000 Gil', 'Dawn Hunt', ARRAY['Complete the FATE ''You Are What You Drink'' three times in succession.', 'Weekly Elite Dawn Hunt — coordinate via Faloop / a hunt Discord for the spawn.'], 'todo'),
(144, 'Atticus the Primogenitor', 'S', 'Elite Dawn Hunt', 'Weekly', 'Heritage Found', 'Heritage Found', 'X:13.9, Y:17.9', 'Weekly Elite mark — conditional spawn', 1, '100 Sacks of Nuts · 5,000 Gil', 'Dawn Hunt', ARRAY['Craft an HQ Rroneek Steak near a spawn point.', 'Weekly Elite Dawn Hunt — coordinate via Faloop / a hunt Discord for the spawn.'], 'todo'),
(145, 'The Forecaster', 'S', 'Elite Dawn Hunt', 'Weekly', 'Living Memory', 'Living Memory', 'X:12.7, Y:27.8', 'Weekly Elite mark — conditional spawn', 1, '100 Sacks of Nuts · 5,000 Gil', 'Dawn Hunt', ARRAY['Cast the Blue Mage spell Northerlies on its spawn points.', 'Weekly Elite Dawn Hunt — coordinate via Faloop / a hunt Discord for the spawn.'], 'todo')
ON CONFLICT (id) DO UPDATE SET
  name=EXCLUDED.name, rank=EXCLUDED.rank, type=EXCLUDED.type, bill_number=EXCLUDED.bill_number,
  zone=EXCLUDED.zone, area=EXCLUDED.area, coords=EXCLUDED.coords, coords_note=EXCLUDED.coords_note,
  targets=EXCLUDED.targets, reward=EXCLUDED.reward, authority=EXCLUDED.authority,
  tips=EXCLUDED.tips, status=EXCLUDED.status;
`;

async function run() {
  await pool.query(sql);
  const { rows } = await pool.query('SELECT id, name, type FROM hunts ORDER BY id');
  console.log(`Seed complete — ${rows.length} marks.`);
  rows.forEach((r) => console.log(`  ${r.id}. [${r.type}] ${r.name}`));
  await pool.end();
}

run().catch((e) => { console.error(e.message); process.exit(1); });
