/* Auto-generated by backend/build-crosslink-nodes.js — DO NOT EDIT BY HAND.
   Gathering catalog entries for recipe-ingredient nodes missing from the main
   (EW/DT endgame) catalogs, so cooking-page deep-links resolve. Node coords &
   windows come from the recipes DB (Teamcraft); zones/levels from Garland Tools. */

export const EXTRA_BOTANY_NODES = [
  {
    "id": "xl-b-856",
    "name": "Lethe",
    "gatherType": "Logging",
    "zone": "Elpis",
    "expansion": "Endwalker",
    "type": "Legendary",
    "coords": "X:33.2, Y:14.8",
    "level": "90",
    "time": "6:00–8:00 ET",
    "window": {
      "open": [
        6,
        0
      ],
      "close": [
        8,
        0
      ]
    },
    "items": [
      {
        "name": "Potent Spice",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-838",
    "name": "Meryall Agronomics",
    "gatherType": "Harvesting",
    "zone": "Labyrinthos",
    "expansion": "Endwalker",
    "type": "Regular",
    "coords": "X:28.0, Y:17.0",
    "level": "85",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Iceberg Lettuce",
        "tag": "common",
        "icon": "herb"
      },
      {
        "name": "Dark Rye",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-848",
    "name": "Reah Tahra",
    "gatherType": "Harvesting",
    "zone": "Ultima Thule",
    "expansion": "Endwalker",
    "type": "Regular",
    "coords": "X:14.2, Y:28.6",
    "level": "90",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Alien Onion",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-846",
    "name": "Anagnorisis",
    "gatherType": "Harvesting",
    "zone": "Elpis",
    "expansion": "Endwalker",
    "type": "Regular",
    "coords": "X:20.8, Y:23.8",
    "level": "90",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Giant Popoto",
        "tag": "common",
        "icon": "herb"
      },
      {
        "name": "Sideritis Leaves",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-844",
    "name": "Southerly Zephyrneus",
    "gatherType": "Logging",
    "zone": "Elpis",
    "expansion": "Endwalker",
    "type": "Regular",
    "coords": "X:9.1, Y:23.2",
    "level": "90",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Sykon",
        "tag": "common",
        "icon": "herb"
      },
      {
        "name": "Elder Nutmeg Seeds",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-843",
    "name": "Liminal Station IV",
    "gatherType": "Harvesting",
    "zone": "Garlemald",
    "expansion": "Endwalker",
    "type": "Regular",
    "coords": "X:25.4, Y:26.2",
    "level": "85",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Eblan Lentils",
        "tag": "common",
        "icon": "herb"
      },
      {
        "name": "Cucumber",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-629",
    "name": "Embrasure",
    "gatherType": "Harvesting",
    "zone": "Lakeland",
    "expansion": "Shadowbringers",
    "type": "Legendary",
    "coords": "X:26.3, Y:20.7",
    "level": "75",
    "time": "10:00–12:00 ET",
    "window": {
      "open": [
        10,
        0
      ],
      "close": [
        12,
        0
      ]
    },
    "items": [
      {
        "name": "Peppermint",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-619",
    "name": "The Deliberating Doll",
    "gatherType": "Harvesting",
    "zone": "The Rak'tika Greatwood",
    "expansion": "Shadowbringers",
    "type": "Regular",
    "coords": "X:14.9, Y:27.2",
    "level": "75",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Royal Grapes",
        "tag": "common",
        "icon": "herb"
      },
      {
        "name": "Creamtop Mushroom",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-617",
    "name": "The Woolen Way",
    "gatherType": "Harvesting",
    "zone": "Il Mheg",
    "expansion": "Shadowbringers",
    "type": "Regular",
    "coords": "X:12.6, Y:22.9",
    "level": "75",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Blood Tomato",
        "tag": "common",
        "icon": "herb"
      },
      {
        "name": "Curly Parsley",
        "tag": "common",
        "icon": "herb"
      },
      {
        "name": "Garden Beet",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-18",
    "name": "Nophica's Wells",
    "gatherType": "Harvesting",
    "zone": "Western Thanalan",
    "expansion": "A Realm Reborn",
    "type": "Regular",
    "coords": "X:23.4, Y:23.4",
    "level": "15",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Garlean Garlic",
        "tag": "common",
        "icon": "herb"
      },
      {
        "name": "Ogre Pumpkin",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-625",
    "name": "Scree",
    "gatherType": "Harvesting",
    "zone": "Kholusia",
    "expansion": "Shadowbringers",
    "type": "Regular",
    "coords": "X:13.6, Y:14.3",
    "level": "80",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Bomba Rice",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-840",
    "name": "Giantsgall Grounds",
    "gatherType": "Harvesting",
    "zone": "Thavnair",
    "expansion": "Endwalker",
    "type": "Regular",
    "coords": "X:21.9, Y:9.6",
    "level": "85",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Thavnairian Paprika",
        "tag": "common",
        "icon": "herb"
      },
      {
        "name": "Thavnairian Perilla Leaf",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-632",
    "name": "Sharptongue Drip",
    "gatherType": "Logging",
    "zone": "Kholusia",
    "expansion": "Shadowbringers",
    "type": "Legendary",
    "coords": "X:20.1, Y:27.3",
    "level": "80",
    "time": "6:00–8:00 ET",
    "window": {
      "open": [
        6,
        0
      ],
      "close": [
        8,
        0
      ]
    },
    "items": [
      {
        "name": "Lemonette",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-134",
    "name": "Bloodshore",
    "gatherType": "Harvesting",
    "zone": "Eastern La Noscea",
    "expansion": "A Realm Reborn",
    "type": "Regular",
    "coords": "X:26.6, Y:30.1",
    "level": "35",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Midland Basil",
        "tag": "common",
        "icon": "herb"
      },
      {
        "name": "Dragon Pepper",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-611",
    "name": "Snitch",
    "gatherType": "Harvesting",
    "zone": "Amh Araeng",
    "expansion": "Stormblood",
    "type": "Regular",
    "coords": "X:32.4, Y:16.8",
    "level": "70",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Night Pepper",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-997",
    "name": "The Ut'ohmu Horizon",
    "gatherType": "Harvesting",
    "zone": "Yak T'el",
    "expansion": "Dawntrail",
    "type": "Regular",
    "coords": "X:19.3, Y:11.8",
    "level": "95",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Ut'ohmu Tomato",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-902",
    "name": "Heimdall's Last Sight",
    "gatherType": "Harvesting",
    "zone": "Mare Lamentorum",
    "expansion": "Endwalker",
    "type": "Regular",
    "coords": "X:34.3, Y:27.7",
    "level": "85",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Carrot of Happiness",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-839",
    "name": "The Great Work",
    "gatherType": "Logging",
    "zone": "Thavnair",
    "expansion": "Endwalker",
    "type": "Regular",
    "coords": "X:16.9, Y:22.3",
    "level": "85",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Palm Syrup",
        "tag": "common",
        "icon": "herb"
      },
      {
        "name": "Coconut",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-27",
    "name": "Silent Arbor",
    "gatherType": "Logging",
    "zone": "South Shroud",
    "expansion": "A Realm Reborn",
    "type": "Regular",
    "coords": "X:26.3, Y:19.1",
    "level": "30",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Alligator Pear",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-343",
    "name": "The Ruling Quarter",
    "gatherType": "Logging",
    "zone": "The Dravanian Hinterlands",
    "expansion": "Heavensward",
    "type": "Legendary",
    "coords": "X:16.1, Y:37.2",
    "level": "60",
    "time": "4:00–6:00 ET",
    "window": {
      "open": [
        4,
        0
      ],
      "close": [
        6,
        0
      ]
    },
    "items": [
      {
        "name": "Cloud Banana",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-23",
    "name": "Nine Ivies",
    "gatherType": "Harvesting",
    "zone": "East Shroud",
    "expansion": "A Realm Reborn",
    "type": "Regular",
    "coords": "X:18.5, Y:28.3",
    "level": "20",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Galago Mint",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-1036",
    "name": "The Ja Tiika Heartland",
    "gatherType": "Logging",
    "zone": "Yak T'el",
    "expansion": "Dawntrail",
    "type": "Regular",
    "coords": "X:19.9, Y:34.8",
    "level": "95",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Wild Ja Tiika Bananas",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-993",
    "name": "Chabayuqeq",
    "gatherType": "Harvesting",
    "zone": "Urqopacha",
    "expansion": "Dawntrail",
    "type": "Regular",
    "coords": "X:28.2, Y:12.0",
    "level": "95",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Turali Aloe",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-988",
    "name": "The Ja Tiika Heartland",
    "gatherType": "Logging",
    "zone": "Yak T'el",
    "expansion": "Dawntrail",
    "type": "Regular",
    "coords": "X:21.5, Y:21.4",
    "level": "95",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Sweet Kukuru Bean",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-995",
    "name": "Uyuypoga",
    "gatherType": "Logging",
    "zone": "Kozama'uka",
    "expansion": "Dawntrail",
    "type": "Regular",
    "coords": "X:32.1, Y:12.0",
    "level": "95",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Turali Pineapple",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-986",
    "name": "Uyuyub'",
    "gatherType": "Logging",
    "zone": "Kozama'uka",
    "expansion": "Dawntrail",
    "type": "Regular",
    "coords": "X:21.6, Y:9.5",
    "level": "95",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Royal Maple Sap",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-1000",
    "name": "The Xobr'it Cinderfield",
    "gatherType": "Harvesting",
    "zone": "Yak T'el",
    "expansion": "Dawntrail",
    "type": "Regular",
    "coords": "X:28.1, Y:14.9",
    "level": "100",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "White Pepper",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-998",
    "name": "The Xobr'it Cinderfield",
    "gatherType": "Harvesting",
    "zone": "Yak T'el",
    "expansion": "Dawntrail",
    "type": "Regular",
    "coords": "X:34.4, Y:22.7",
    "level": "95",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Turali Corn",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-999",
    "name": "Yawtanane Grasslands",
    "gatherType": "Harvesting",
    "zone": "Shaaloani",
    "expansion": "Dawntrail",
    "type": "Regular",
    "coords": "X:31.2, Y:24.7",
    "level": "95",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Shaaloani Oilseeds",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-1004",
    "name": "Blooms of Discovery",
    "gatherType": "Harvesting",
    "zone": "Living Memory",
    "expansion": "Dawntrail",
    "type": "Regular",
    "coords": "X:17.0, Y:17.9",
    "level": "100",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Wind Parsley",
        "tag": "common",
        "icon": "herb"
      },
      {
        "name": "Broccoli",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-1003",
    "name": "Everkeep Ward",
    "gatherType": "Harvesting",
    "zone": "Heritage Found",
    "expansion": "Dawntrail",
    "type": "Regular",
    "coords": "X:11.4, Y:17.4",
    "level": "100",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Yyasulani Garlic",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-989",
    "name": "Eshceyaani Wilds",
    "gatherType": "Logging",
    "zone": "Shaaloani",
    "expansion": "Dawntrail",
    "type": "Regular",
    "coords": "X:12.3, Y:22.1",
    "level": "100",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Mesquite Beans",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-1002",
    "name": "Yawtanane Grasslands",
    "gatherType": "Harvesting",
    "zone": "Shaaloani",
    "expansion": "Dawntrail",
    "type": "Regular",
    "coords": "X:23.1, Y:33.7",
    "level": "100",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Bell Pepper",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-631",
    "name": "Bowrest",
    "gatherType": "Harvesting",
    "zone": "The Rak'tika Greatwood",
    "expansion": "Shadowbringers",
    "type": "Legendary",
    "coords": "X:34.7, Y:21.6",
    "level": "80",
    "time": "0:00–2:00 ET",
    "window": {
      "open": [
        0,
        0
      ],
      "close": [
        2,
        0
      ]
    },
    "items": [
      {
        "name": "Mist Spinach",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-13",
    "name": "Treespeak",
    "gatherType": "Logging",
    "zone": "North Shroud",
    "expansion": "A Realm Reborn",
    "type": "Regular",
    "coords": "X:26.5, Y:27.4",
    "level": "5",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Cinnamon",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-615",
    "name": "Woven Oath",
    "gatherType": "Logging",
    "zone": "The Rak'tika Greatwood",
    "expansion": "Shadowbringers",
    "type": "Regular",
    "coords": "X:10.1, Y:20.6",
    "level": "75",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Gianthive Chip",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-618",
    "name": "Seagazer",
    "gatherType": "Harvesting",
    "zone": "Kholusia",
    "expansion": "Shadowbringers",
    "type": "Regular",
    "coords": "X:16.4, Y:36.2",
    "level": "75",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Upland Wheat",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-297",
    "name": "Chocobo Forest",
    "gatherType": "Harvesting",
    "zone": "The Dravanian Forelands",
    "expansion": "Heavensward",
    "type": "Regular",
    "coords": "X:37.6, Y:19.6",
    "level": "55",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Highland Wheat",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-511",
    "name": "Rasen Kaikyo",
    "gatherType": "Harvesting",
    "zone": "The Ruby Sea",
    "expansion": "Stormblood",
    "type": "Regular",
    "coords": "X:27.2, Y:22.0",
    "level": "65",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Gem Algae",
        "tag": "common",
        "icon": "herb"
      }
    ]
  },
  {
    "id": "xl-b-612",
    "name": "The Chiliad",
    "gatherType": "Logging",
    "zone": "Lakeland",
    "expansion": "Shadowbringers",
    "type": "Regular",
    "coords": "X:35.4, Y:24.9",
    "level": "75",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Frantoio",
        "tag": "common",
        "icon": "herb"
      }
    ]
  }
]

export const EXTRA_MINING_NODES = [
  {
    "id": "xl-m-287",
    "name": "The Smoldering Wastes",
    "gatherType": "Mining",
    "zone": "The Dravanian Forelands",
    "expansion": "Heavensward",
    "type": "Regular",
    "coords": "X:27.5, Y:31.9",
    "level": "55",
    "time": "Any",
    "window": null,
    "items": [
      {
        "name": "Dravanian Spring Water",
        "tag": "common",
        "icon": "ore"
      }
    ]
  },
  {
    "id": "xl-m-318",
    "name": "The Gauntlet",
    "gatherType": "Quarrying",
    "zone": "The Sea of Clouds",
    "expansion": "Heavensward",
    "type": "Legendary",
    "coords": "X:7.8, Y:7.6",
    "level": "60",
    "time": "10:00–12:00 ET",
    "window": {
      "open": [
        10,
        0
      ],
      "close": [
        12,
        0
      ]
    },
    "items": [
      {
        "name": "Abalathian Rock Salt",
        "tag": "common",
        "icon": "gem"
      }
    ]
  }
]

export const EXTRA_FISHING_SPOTS = [
  {
    "id": "xl-f-51",
    "name": "South Bloodshore",
    "zone": "Eastern La Noscea",
    "expansion": "A Realm Reborn",
    "coords": "X:32.9, Y:34.5",
    "weather": null,
    "time": "Any",
    "baits": [],
    "fish": [
      {
        "name": "Bianaq Bream",
        "rarity": "common",
        "note": ""
      }
    ]
  },
  {
    "id": "xl-f-2",
    "name": "The Vein",
    "zone": "Central Shroud",
    "expansion": "A Realm Reborn",
    "coords": "X:22.9, Y:22.2",
    "weather": null,
    "time": "Any",
    "baits": [],
    "fish": [
      {
        "name": "Brass Loach",
        "rarity": "common",
        "note": ""
      }
    ]
  }
]

// Short badge labels for node/spot cards — extras span all expansions.
export const EXP_SHORT = {
  'A Realm Reborn': 'ARR', Heavensward: 'HW', Stormblood: 'SB',
  Shadowbringers: 'ShB', Endwalker: 'EW', Dawntrail: 'DT',
}
