/* Auto-generated by backend/scripts/build-fish-conditions.mjs — DO NOT EDIT BY HAND.
   Catch conditions for restricted fish in our catalog: required weather
   (current / previous Eorzean weather period), ET hour window, bait chain.
   Consumed by src/eorzeaWeather.js nextFishWindow() for live countdowns.
   Source: ff14-fish-tracker-app + Teamcraft + Garland. */

export const FISH_CONDITIONS = {
  "Aetherolectric Guitarfish": {
    "weather": [],
    "prevWeather": [],
    "start": 20,
    "end": 24,
    "bait": [
      "Mackerel Strip"
    ]
  },
  "Antheian Dahlia": {
    "weather": [
      "Clear Skies"
    ],
    "prevWeather": [
      "Clouds"
    ],
    "start": 4,
    "end": 10,
    "bait": [
      "Mayfly"
    ]
  },
  "Argonauta argo": {
    "weather": [
      "Umbral Wind"
    ],
    "prevWeather": [],
    "start": 2,
    "end": 4,
    "bait": [
      "Stardust"
    ]
  },
  "Autarch's Supper": {
    "weather": [
      "Fog"
    ],
    "prevWeather": [
      "Rain"
    ],
    "start": 16,
    "end": 18,
    "bait": [
      "Red Maggots"
    ]
  },
  "Awaksbane Apoda": {
    "weather": [
      "Clouds",
      "Fog"
    ],
    "prevWeather": [],
    "start": 0,
    "end": 24,
    "bait": [
      "Red Maggots"
    ]
  },
  "Azure Diver": {
    "weather": [
      "Gales"
    ],
    "prevWeather": [
      "Clear Skies",
      "Fair Skies"
    ],
    "start": 18,
    "end": 24,
    "bait": [
      "Dragonfly"
    ]
  },
  "Basilosaurus": {
    "weather": [
      "Fair Skies"
    ],
    "prevWeather": [],
    "start": 0,
    "end": 24,
    "bait": [
      "Mackerel Strip",
      "Puff-paya"
    ]
  },
  "Basilosaurus Rex": {
    "weather": [
      "Fair Skies"
    ],
    "prevWeather": [],
    "start": 0,
    "end": 24,
    "bait": [
      "Mackerel Strip",
      "Puff-paya",
      "Basilosaurus"
    ]
  },
  "Bigcuda": {
    "weather": [
      "Rain",
      "Showers"
    ],
    "prevWeather": [
      "Clear Skies",
      "Fair Skies"
    ],
    "start": 8,
    "end": 16,
    "bait": [
      "Sky Spoon Lure"
    ]
  },
  "Browned Banana Eel": {
    "weather": [
      "Rain"
    ],
    "prevWeather": [],
    "start": 22,
    "end": 2,
    "bait": [
      "Mayfly"
    ]
  },
  "Cabinkeep Permit": {
    "weather": [],
    "prevWeather": [],
    "start": 5,
    "end": 7,
    "bait": [
      "Ghost Nipper"
    ]
  },
  "Catastrophizer": {
    "weather": [
      "Clear Skies"
    ],
    "prevWeather": [
      "Fair Skies"
    ],
    "start": 8,
    "end": 14,
    "bait": [
      "Mayfly"
    ]
  },
  "Cazuela Crab": {
    "weather": [
      "Clouds",
      "Fog"
    ],
    "prevWeather": [],
    "start": 16,
    "end": 20,
    "bait": [
      "Red Maggots"
    ]
  },
  "Chain Shark": {
    "weather": [],
    "prevWeather": [],
    "start": 18,
    "end": 20,
    "bait": [
      "Sharknose Goby",
      "Yak T'el Crab"
    ]
  },
  "Chlorophos Deathworm": {
    "weather": [
      "Astromagnetic Storms"
    ],
    "prevWeather": [
      "Fair Skies"
    ],
    "start": 2,
    "end": 8,
    "bait": [
      "Chimera Worm",
      "Calicia"
    ]
  },
  "Circuit Tilapia": {
    "weather": [
      "Fair Skies"
    ],
    "prevWeather": [
      "Clouds"
    ],
    "start": 8,
    "end": 12,
    "bait": [
      "Mayfly",
      "Astacus Aetherius"
    ]
  },
  "Copper Shark": {
    "weather": [
      "Clouds",
      "Fog"
    ],
    "prevWeather": [],
    "start": 0,
    "end": 24,
    "bait": [
      "Ghost Nipper"
    ]
  },
  "Cosmic Haze": {
    "weather": [
      "Apocalypse"
    ],
    "prevWeather": [],
    "start": 20,
    "end": 4,
    "bait": [
      "Chimera Worm",
      "Vacuum Shrimp"
    ]
  },
  "Crenicichla Miyaka": {
    "weather": [
      "Rain"
    ],
    "prevWeather": [],
    "start": 6,
    "end": 8,
    "bait": [
      "Red Maggots"
    ]
  },
  "Datnioides Aeroplanos": {
    "weather": [
      "Rain"
    ],
    "prevWeather": [
      "Fog"
    ],
    "start": 2,
    "end": 4,
    "bait": [
      "Red Maggots"
    ]
  },
  "Deep Canopy": {
    "weather": [],
    "prevWeather": [],
    "start": 10,
    "end": 12,
    "bait": [
      "Red Maggots"
    ]
  },
  "Disappirarucu": {
    "weather": [],
    "prevWeather": [],
    "start": 0,
    "end": 2,
    "bait": [
      "Mayfly"
    ]
  },
  "Durdina Fish": {
    "weather": [
      "Clear Skies"
    ],
    "prevWeather": [
      "Fair Skies"
    ],
    "start": 0,
    "end": 4,
    "bait": [
      "Shrimp Ball",
      "Shadowdart Sardine"
    ]
  },
  "E.B.E.-852738": {
    "weather": [
      "Umbral Wind"
    ],
    "prevWeather": [
      "Fair Skies"
    ],
    "start": 12,
    "end": 16,
    "bait": [
      "Stardust"
    ]
  },
  "Earful": {
    "weather": [],
    "prevWeather": [],
    "start": 4,
    "end": 8,
    "bait": [
      "Mayfly"
    ]
  },
  "Eehs Fan": {
    "weather": [
      "Umbral Wind"
    ],
    "prevWeather": [
      "Apocalypse"
    ],
    "start": 12,
    "end": 20,
    "bait": [
      "Chimera Worm"
    ]
  },
  "Esperance Carp": {
    "weather": [
      "Clouds"
    ],
    "prevWeather": [
      "Rain"
    ],
    "start": 22,
    "end": 24,
    "bait": [
      "Red Maggots"
    ]
  },
  "Excavator Catfish": {
    "weather": [
      "Clouds"
    ],
    "prevWeather": [
      "Rain"
    ],
    "start": 4,
    "end": 6,
    "bait": [
      "Popper Lure"
    ]
  },
  "Forbiddingway": {
    "weather": [
      "Apocalypse"
    ],
    "prevWeather": [],
    "start": 8,
    "end": 12,
    "bait": [
      "Stardust"
    ]
  },
  "Foun Ahlm": {
    "weather": [
      "Umbral Wind"
    ],
    "prevWeather": [],
    "start": 10,
    "end": 14,
    "bait": [
      "Chimera Worm"
    ]
  },
  "Frozen Regotoise": {
    "weather": [
      "Umbral Wind"
    ],
    "prevWeather": [],
    "start": 10,
    "end": 13,
    "bait": [
      "Chimera Worm"
    ]
  },
  "Furcacauda": {
    "weather": [
      "Umbral Wind"
    ],
    "prevWeather": [
      "Fair Skies"
    ],
    "start": 15.5,
    "end": 16.5,
    "bait": [
      "Sky Spoon Lure"
    ]
  },
  "Gharlichthys": {
    "weather": [
      "Fair Skies"
    ],
    "prevWeather": [
      "Showers"
    ],
    "start": 14,
    "end": 16,
    "bait": [
      "Mackerel Strip"
    ]
  },
  "Gigagiant Snakehead": {
    "weather": [
      "Rain"
    ],
    "prevWeather": [],
    "start": 4,
    "end": 6,
    "bait": [
      "Red Maggots"
    ]
  },
  "Gilt Dermogenys": {
    "weather": [
      "Clear Skies",
      "Fair Skies"
    ],
    "prevWeather": [
      "Umbral Wind"
    ],
    "start": 20,
    "end": 22,
    "bait": [
      "Sky Spoon Lure"
    ]
  },
  "Gondola Louvar": {
    "weather": [
      "Fair Skies"
    ],
    "prevWeather": [
      "Rain"
    ],
    "start": 8,
    "end": 12,
    "bait": [
      "Ghost Nipper"
    ]
  },
  "Greatsword Snook": {
    "weather": [
      "Snow"
    ],
    "prevWeather": [],
    "start": 16,
    "end": 20,
    "bait": [
      "Mayfly"
    ]
  },
  "Harlequin Queen": {
    "weather": [
      "Fair Skies"
    ],
    "prevWeather": [],
    "start": 16,
    "end": 18,
    "bait": [
      "Red Maggots"
    ]
  },
  "Heirloom Goldgrouper": {
    "weather": [
      "Fair Skies"
    ],
    "prevWeather": [
      "Fog"
    ],
    "start": 12,
    "end": 16,
    "bait": [
      "Popper Lure"
    ]
  },
  "Hippo Frog": {
    "weather": [
      "Showers"
    ],
    "prevWeather": [],
    "start": 0,
    "end": 24,
    "bait": [
      "Mayfly"
    ]
  },
  "Horned Frog": {
    "weather": [],
    "prevWeather": [],
    "start": 0,
    "end": 2,
    "bait": [
      "Cloud-eye Carp"
    ]
  },
  "Hwittayoanaan Cichlid": {
    "weather": [
      "Clear Skies",
      "Fair Skies"
    ],
    "prevWeather": [],
    "start": 4,
    "end": 8,
    "bait": [
      "Red Maggots"
    ]
  },
  "Hyphalosaurus": {
    "weather": [
      "Fair Skies"
    ],
    "prevWeather": [
      "Clear Skies"
    ],
    "start": 9,
    "end": 12,
    "bait": [
      "Mayfly",
      "Astacus Aetherius"
    ]
  },
  "Icuvlo's Barter": {
    "weather": [
      "Fog"
    ],
    "prevWeather": [],
    "start": 0,
    "end": 24,
    "bait": [
      "Red Maggots"
    ]
  },
  "Ilyon Asoh Cichlid": {
    "weather": [
      "Clear Skies"
    ],
    "prevWeather": [],
    "start": 0,
    "end": 24,
    "bait": [
      "Red Maggots"
    ]
  },
  "Iron Oxydoras": {
    "weather": [
      "Fog"
    ],
    "prevWeather": [
      "Clouds"
    ],
    "start": 13,
    "end": 15,
    "bait": [
      "Golden Stonefly Nymph",
      "Dumplingfish"
    ]
  },
  "Iron Shadowtongue": {
    "weather": [
      "Rain"
    ],
    "prevWeather": [],
    "start": 16,
    "end": 18,
    "bait": [
      "Red Maggots"
    ]
  },
  "Jumbo Snook": {
    "weather": [
      "Clouds"
    ],
    "prevWeather": [],
    "start": 18,
    "end": 22,
    "bait": [
      "Mayfly"
    ]
  },
  "Labyrinthos Tilapia": {
    "weather": [
      "Fair Skies"
    ],
    "prevWeather": [],
    "start": 8,
    "end": 16,
    "bait": [
      "Leech",
      "Astacus Aetherius"
    ]
  },
  "Lale Crab": {
    "weather": [
      "Fog"
    ],
    "prevWeather": [
      "Clear Skies",
      "Fair Skies"
    ],
    "start": 0,
    "end": 24,
    "bait": [
      "Shrimp Ball"
    ]
  },
  "Lopoceras Elegans": {
    "weather": [
      "Fair Skies"
    ],
    "prevWeather": [
      "Astromagnetic Storms"
    ],
    "start": 8,
    "end": 10,
    "bait": [
      "Chimera Worm"
    ]
  },
  "Lotl-in-waiting": {
    "weather": [
      "Clouds"
    ],
    "prevWeather": [
      "Fair Skies"
    ],
    "start": 0,
    "end": 4,
    "bait": [
      "Cloud-eye Carp"
    ]
  },
  "Lunar Deathworm": {
    "weather": [
      "Fair Skies"
    ],
    "prevWeather": [],
    "start": 0,
    "end": 24,
    "bait": [
      "Grey Worm",
      "Calicia"
    ]
  },
  "Mangar": {
    "weather": [
      "Clouds"
    ],
    "prevWeather": [],
    "start": 0,
    "end": 24,
    "bait": [
      "Mayfly",
      "Albino Loach"
    ]
  },
  "Mayaman": {
    "weather": [
      "Fair Skies"
    ],
    "prevWeather": [
      "Clouds"
    ],
    "start": 4,
    "end": 8,
    "bait": [
      "Mayfly"
    ]
  },
  "Mayashell": {
    "weather": [],
    "prevWeather": [],
    "start": 3,
    "end": 6,
    "bait": [
      "Mayfly",
      "Handy Hamsa"
    ]
  },
  "Moongripper": {
    "weather": [],
    "prevWeather": [],
    "start": 12,
    "end": 14,
    "bait": [
      "White Worm"
    ]
  },
  "Moonmarking Saucer": {
    "weather": [
      "Rain"
    ],
    "prevWeather": [
      "Clear Skies"
    ],
    "start": 16,
    "end": 21,
    "bait": [
      "Red Maggots",
      "Flawless Saucer"
    ]
  },
  "Mossgill Salmon": {
    "weather": [
      "Rain"
    ],
    "prevWeather": [
      "Clouds"
    ],
    "start": 0,
    "end": 24,
    "bait": [
      "Sky Spoon Lure"
    ]
  },
  "Moxutural Greatgar": {
    "weather": [
      "Rain"
    ],
    "prevWeather": [],
    "start": 20,
    "end": 22,
    "bait": [
      "Popper Lure",
      "Checkered Cichlid"
    ]
  },
  "Muttering Matamata": {
    "weather": [
      "Clear Skies"
    ],
    "prevWeather": [],
    "start": 12,
    "end": 14,
    "bait": [
      "Poison Dyefrog"
    ]
  },
  "Ole Ole Ole": {
    "weather": [
      "Snow"
    ],
    "prevWeather": [
      "Clouds"
    ],
    "start": 0,
    "end": 2,
    "bait": [
      "White Worm"
    ]
  },
  "Onyx Knifefish": {
    "weather": [
      "Fair Skies"
    ],
    "prevWeather": [
      "Rain"
    ],
    "start": 22,
    "end": 2,
    "bait": [
      "Mayfly"
    ]
  },
  "Phyllinos": {
    "weather": [],
    "prevWeather": [],
    "start": 5,
    "end": 8,
    "bait": [
      "Mayfly"
    ]
  },
  "Pixel Loach": {
    "weather": [],
    "prevWeather": [],
    "start": 0,
    "end": 4,
    "bait": [
      "Red Maggots"
    ]
  },
  "Planetes": {
    "weather": [
      "Umbral Wind"
    ],
    "prevWeather": [],
    "start": 0,
    "end": 24,
    "bait": [
      "Mayfly",
      "Albino Loach"
    ]
  },
  "Prime Adjudicator": {
    "weather": [
      "Fog"
    ],
    "prevWeather": [
      "Fair Skies"
    ],
    "start": 12,
    "end": 16,
    "bait": [
      "Red Maggots"
    ]
  },
  "Punutiy Pain": {
    "weather": [
      "Rain"
    ],
    "prevWeather": [
      "Clouds"
    ],
    "start": 8,
    "end": 12,
    "bait": [
      "Hunu Peacock Bass"
    ]
  },
  "Purse of Riches": {
    "weather": [
      "Rain"
    ],
    "prevWeather": [
      "Clouds"
    ],
    "start": 16,
    "end": 18,
    "bait": [
      "Ghost Nipper"
    ]
  },
  "Red Drum": {
    "weather": [
      "Fair Skies"
    ],
    "prevWeather": [],
    "start": 16,
    "end": 24,
    "bait": [
      "Mayfly"
    ]
  },
  "Rimepike": {
    "weather": [
      "Snow"
    ],
    "prevWeather": [],
    "start": 0,
    "end": 24,
    "bait": [
      "Mayfly",
      "Cerule Core"
    ]
  },
  "Riverlong Candiru": {
    "weather": [
      "Clouds"
    ],
    "prevWeather": [
      "Fair Skies"
    ],
    "start": 0,
    "end": 4,
    "bait": [
      "Red Maggots"
    ]
  },
  "Shin Snuffler": {
    "weather": [
      "Fog"
    ],
    "prevWeather": [],
    "start": 0,
    "end": 2,
    "bait": [
      "Red Maggots"
    ]
  },
  "Shined Copper Shark": {
    "weather": [
      "Fog"
    ],
    "prevWeather": [
      "Clouds"
    ],
    "start": 8,
    "end": 13,
    "bait": [
      "Ghost Nipper"
    ]
  },
  "Shuckfin Dace": {
    "weather": [
      "Rain"
    ],
    "prevWeather": [],
    "start": 4,
    "end": 6,
    "bait": [
      "Red Maggots"
    ]
  },
  "Sidereal Whale": {
    "weather": [
      "Apocalypse"
    ],
    "prevWeather": [
      "Umbral Wind"
    ],
    "start": 0,
    "end": 8,
    "bait": [
      "Horizon Event"
    ]
  },
  "Snowy Parexus": {
    "weather": [
      "Snow"
    ],
    "prevWeather": [
      "Fair Skies"
    ],
    "start": 16,
    "end": 24,
    "bait": [
      "Mayfly"
    ]
  },
  "Sovereign Shadow": {
    "weather": [
      "Snow"
    ],
    "prevWeather": [
      "Clouds",
      "Fog"
    ],
    "start": 2,
    "end": 8,
    "bait": [
      "Mayfly"
    ]
  },
  "Sprouting Perch": {
    "weather": [
      "Thunderstorms"
    ],
    "prevWeather": [],
    "start": 20,
    "end": 24,
    "bait": [
      "Red Maggots"
    ]
  },
  "Stardust Sleeper": {
    "weather": [],
    "prevWeather": [],
    "start": 20,
    "end": 24,
    "bait": [
      "Sharknose Goby",
      "Yak T'el Crab"
    ]
  },
  "Stargilt Lobster": {
    "weather": [],
    "prevWeather": [],
    "start": 19,
    "end": 22,
    "bait": [
      "Grey Worm"
    ]
  },
  "Starscale Ephemeris": {
    "weather": [
      "Fair Skies"
    ],
    "prevWeather": [
      "Apocalypse"
    ],
    "start": 18,
    "end": 22,
    "bait": [
      "Mayfly"
    ]
  },
  "Starscryer": {
    "weather": [
      "Apocalypse"
    ],
    "prevWeather": [],
    "start": 2,
    "end": 4,
    "bait": [
      "Mayfly"
    ]
  },
  "Swampsucker Bowfin": {
    "weather": [
      "Clouds"
    ],
    "prevWeather": [
      "Clear Skies",
      "Fair Skies"
    ],
    "start": 8,
    "end": 16,
    "bait": [
      "Sky Spoon Lure"
    ]
  },
  "The Fury's Aegis": {
    "weather": [],
    "prevWeather": [],
    "start": 16,
    "end": 19,
    "bait": [
      "Leech"
    ]
  },
  "Thunderous Flounder": {
    "weather": [
      "Rain"
    ],
    "prevWeather": [],
    "start": 0,
    "end": 24,
    "bait": [
      "Red Maggots"
    ]
  },
  "Thunderswift Trout": {
    "weather": [],
    "prevWeather": [],
    "start": 9,
    "end": 11,
    "bait": [
      "Red Maggots"
    ]
  },
  "Ttokatoa": {
    "weather": [
      "Dust Storms"
    ],
    "prevWeather": [
      "Fair Skies"
    ],
    "start": 20,
    "end": 24,
    "bait": [
      "Popper Lure",
      "Niikwerepi Trout"
    ]
  },
  "Urqofrog": {
    "weather": [],
    "prevWeather": [],
    "start": 20,
    "end": 24,
    "bait": [
      "Red Maggots"
    ]
  },
  "Vagrant Keeper": {
    "weather": [
      "Clouds"
    ],
    "prevWeather": [
      "Gales"
    ],
    "start": 6,
    "end": 8,
    "bait": [
      "Dragonfly"
    ]
  },
  "Vidyutvat Wrasse": {
    "weather": [
      "Clear Skies"
    ],
    "prevWeather": [
      "Clouds"
    ],
    "start": 20,
    "end": 24,
    "bait": [
      "Shrimp Ball"
    ]
  },
  "Wakeful Warden": {
    "weather": [
      "Clouds"
    ],
    "prevWeather": [
      "Fog"
    ],
    "start": 0,
    "end": 24,
    "bait": [
      "Leech"
    ]
  },
  "Yellow Peacock Bass": {
    "weather": [],
    "prevWeather": [],
    "start": 12,
    "end": 13,
    "bait": [
      "Dumplingfish"
    ]
  }
}
