/* ============================================================
   fishingData.js — fishing spot catalog (auto-generated).
   Sources: ffxiv.consolegameswiki.com Dawntrail + Endwalker
            fishing location pages.
   Weather, time windows, and timed flags are defaults — enrich
   individual entries as needed.
   ============================================================ */

export const FISHING_SPOTS = [
  {
    id: 'tuli-downripple', name: 'Downripple', zone: 'Tuliyollal', expansion: 'Dawntrail',
    coords: 'X:9, Y:10.5', weather: null, time: 'Any',
    baits: [['Honeybee', '#e8c84e'], ['Versatile Lure', '#74e3dc'], ['Popper Lure', '#e87c4e'], ['Golden Stonefly Nymph', '#e8c84e']],
    fish: [
      { name: 'Mosquito Fish', rarity: 'common', note: '' },
      { name: 'Pel Frog', rarity: 'common', note: '' },
      { name: 'Petticoat Tetra', rarity: 'common', note: '' },
      { name: 'Icuvlo\'s Barter', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'tuli-the-for-ard-cabins', name: 'The For\'ard Cabins', zone: 'Tuliyollal', expansion: 'Dawntrail',
    coords: 'X:10, Y:19', weather: null, time: 'Any',
    baits: [['Metal Spinner', '#8fb6d6'], ['Versatile Lure', '#74e3dc'], ['Crimson Lugworm', '#d65858'], ['Ghost Nipper', '#8fb6d6']],
    fish: [
      { name: 'Stardust Shrimp', rarity: 'legendary', note: '' },
      { name: 'Reasonscale Silverside', rarity: 'rare', note: '' },
      { name: 'Shallows Sot', rarity: 'common', note: '' },
      { name: 'Ghostfish', rarity: 'rare', note: '' },
      { name: 'Permit', rarity: 'rare', note: '' },
      { name: 'Inktopus', rarity: 'common', note: '' },
      { name: 'Cabinkeep Permit', rarity: 'rare', note: '' },
    ],
  },
  {
    id: 'tuli-hightide-harbor', name: 'Hightide Harbor', zone: 'Tuliyollal', expansion: 'Dawntrail',
    coords: 'X:16, Y:14', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Crimson Lugworm', '#d65858'], ['Ghost Nipper', '#8fb6d6'], ['Shucked Clam', '#c4b8a0']],
    fish: [
      { name: 'King Puffer', rarity: 'rare', note: '' },
      { name: 'Blue Purse', rarity: 'common', note: '' },
      { name: 'Floating Fife', rarity: 'rare', note: '' },
      { name: 'Reasonscale Silverside', rarity: 'rare', note: '' },
      { name: 'Goldfin Cavalli', rarity: 'rare', note: '' },
      { name: 'Purse of Riches', rarity: 'rare', note: '' },
    ],
  },
  {
    id: 'urqo-sunken-stars', name: 'Sunken Stars', zone: 'Urqopacha', expansion: 'Dawntrail',
    coords: 'X:20, Y:27', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Silkmoth Pupa', '#74e3dc'], ['White Worm', '#74e3dc']],
    fish: [
      { name: 'Urqotrout', rarity: 'common', note: '' },
      { name: 'Sea Alpaca', rarity: 'common', note: '' },
      { name: 'Marbled Hatchetfish', rarity: 'common', note: '' },
      { name: 'Starsnipper', rarity: 'legendary', note: '' },
      { name: 'Yok Huy Stonecutter', rarity: 'common', note: '' },
      { name: 'Moongripper', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'urqo-chirwagur-lake', name: 'Chirwagur Lake', zone: 'Urqopacha', expansion: 'Dawntrail',
    coords: 'X:20, Y:36', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Silkmoth Pupa', '#74e3dc'], ['White Worm', '#74e3dc']],
    fish: [
      { name: 'Chirwagur Loach', rarity: 'common', note: '' },
      { name: 'Alright Alright Alright', rarity: 'common', note: '' },
      { name: 'Shooting Starscale', rarity: 'legendary', note: '' },
      { name: 'Zorlortor', rarity: 'common', note: '' },
      { name: 'Ole Ole Ole', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'urqo-karvarhur-the-first', name: 'Karvarhur the First', zone: 'Urqopacha', expansion: 'Dawntrail',
    coords: 'X:6, Y:20', weather: null, time: 'Any',
    baits: [['Honeybee', '#e8c84e'], ['Versatile Lure', '#74e3dc'], ['Popper Lure', '#e87c4e'], ['Golden Stonefly Nymph', '#e8c84e']],
    fish: [
      { name: 'First Feastfish', rarity: 'common', note: '' },
      { name: 'Urqofrog', rarity: 'common', note: '' },
      { name: 'Zeh Tortoh', rarity: 'common', note: '' },
      { name: 'Morsel Trout', rarity: 'common', note: '' },
      { name: 'Deepwarden', rarity: 'common', note: '' },
      { name: 'Qor Pirarucu', rarity: 'common', note: '' },
      { name: 'Prime Adjudicator', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'koza-bopo-uihih', name: 'Bopo\'uihih', zone: 'Kozama\'uka', expansion: 'Dawntrail',
    coords: 'X:10, Y:12', weather: null, time: 'Any',
    baits: [['Metal Spinner', '#8fb6d6'], ['Honeybee', '#e8c84e'], ['Versatile Lure', '#74e3dc'], ['Popper Lure', '#e87c4e']],
    fish: [
      { name: 'Kozama\'uka Skipper', rarity: 'common', note: '' },
      { name: 'Bopo\'u Sleeper', rarity: 'common', note: '' },
      { name: 'Poison Dyefrog', rarity: 'common', note: '' },
      { name: 'Pleated Matamata', rarity: 'common', note: '' },
      { name: 'Uyuy Xage', rarity: 'common', note: '' },
      { name: 'Oily Ropefish', rarity: 'common', note: '' },
      { name: 'Muttering Matamata', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'koza-waters-hanu', name: 'Waters Hanu', zone: 'Kozama\'uka', expansion: 'Dawntrail',
    coords: 'X:23, Y:13', weather: null, time: 'Any',
    baits: [['Metal Spinner', '#8fb6d6'], ['Honeybee', '#e8c84e'], ['Versatile Lure', '#74e3dc'], ['Popper Lure', '#e87c4e']],
    fish: [
      { name: 'Kozama\'uka Skipper', rarity: 'common', note: '' },
      { name: 'Bopo\'u Sleeper', rarity: 'common', note: '' },
      { name: 'Plattershell', rarity: 'common', note: '' },
      { name: 'Yok Huy Pleco', rarity: 'common', note: '' },
      { name: 'Cazuela Crab', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'koza-miyakabek-zu', name: 'Miyakabek\'zu', zone: 'Kozama\'uka', expansion: 'Dawntrail',
    coords: 'X:29, Y:12', weather: null, time: 'Any',
    baits: [['Metal Spinner', '#8fb6d6'], ['Honeybee', '#e8c84e'], ['Versatile Lure', '#74e3dc'], ['Popper Lure', '#e87c4e']],
    fish: [
      { name: 'Driftwood Catfish', rarity: 'common', note: '' },
      { name: 'Kozama\'uka Skipper', rarity: 'common', note: '' },
      { name: 'Bopo\'u Sleeper', rarity: 'common', note: '' },
      { name: 'Candiru', rarity: 'common', note: '' },
      { name: 'Trahira', rarity: 'common', note: '' },
      { name: 'Riverlong Candiru', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'koza-the-dewspun-bank', name: 'The Dewspun Bank', zone: 'Kozama\'uka', expansion: 'Dawntrail',
    coords: 'X:38, Y:33', weather: null, time: 'Any',
    baits: [['Honeybee', '#e8c84e'], ['Versatile Lure', '#74e3dc'], ['Popper Lure', '#e87c4e'], ['Golden Stonefly Nymph', '#e8c84e']],
    fish: [
      { name: 'Oho Hunu', rarity: 'common', note: '' },
      { name: 'Bronze Pleco', rarity: 'common', note: '' },
      { name: 'Crenicichla', rarity: 'common', note: '' },
      { name: 'Crenicichla Miyaka', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'koza-peaks-poga', name: 'Peaks Poga', zone: 'Kozama\'uka', expansion: 'Dawntrail',
    coords: 'X:40, Y:15', weather: null, time: 'Any',
    baits: [['Honeybee', '#e8c84e'], ['Versatile Lure', '#74e3dc'], ['Popper Lure', '#e87c4e'], ['Golden Stonefly Nymph', '#e8c84e']],
    fish: [
      { name: 'Oho Hunu', rarity: 'common', note: '' },
      { name: 'Bronze Pleco', rarity: 'common', note: '' },
      { name: 'Hunu Peacock Bass', rarity: 'common', note: '' },
      { name: 'Pelubane', rarity: 'common', note: '' },
      { name: 'Giant Trahira', rarity: 'rare', note: '' },
      { name: 'Punutiy Pain', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'koza-ku-uxage', name: 'Ku\'uxage', zone: 'Kozama\'uka', expansion: 'Dawntrail',
    coords: 'X:22, Y:21', weather: null, time: 'Any',
    baits: [['Honeybee', '#e8c84e'], ['Versatile Lure', '#74e3dc'], ['Popper Lure', '#e87c4e'], ['Golden Stonefly Nymph', '#e8c84e']],
    fish: [
      { name: 'Red Maggots', rarity: 'common', note: '' },
      { name: 'Ku\'uxage Bitterling', rarity: 'common', note: '' },
      { name: 'Tonguesnatcher', rarity: 'common', note: '' },
      { name: 'Corn Dace', rarity: 'common', note: '' },
      { name: 'Ka Puyhu', rarity: 'common', note: '' },
      { name: 'Purple Palate', rarity: 'common', note: '' },
      { name: 'Shuckfin Dace', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'koza-miyakabek-zoma', name: 'Miyakabek\'zoma', zone: 'Kozama\'uka', expansion: 'Dawntrail',
    coords: 'X:14, Y:28', weather: null, time: 'Any',
    baits: [['Metal Spinner', '#8fb6d6'], ['Honeybee', '#e8c84e'], ['Versatile Lure', '#74e3dc'], ['Popper Lure', '#e87c4e']],
    fish: [
      { name: 'Dumplingfish', rarity: 'common', note: '' },
      { name: 'Banded Candiru', rarity: 'common', note: '' },
      { name: 'Oxydoras', rarity: 'common', note: '' },
      { name: 'Ligaka Guppy', rarity: 'common', note: '' },
      { name: 'Honeycomb Sponge', rarity: 'common', note: '' },
      { name: 'Iron Oxydoras', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'koza-marsh-ligaka', name: 'Marsh Ligaka', zone: 'Kozama\'uka', expansion: 'Dawntrail',
    coords: 'X:25, Y:31', weather: null, time: 'Any',
    baits: [['Metal Spinner', '#8fb6d6'], ['Honeybee', '#e8c84e'], ['Versatile Lure', '#74e3dc'], ['Popper Lure', '#e87c4e']],
    fish: [
      { name: 'Dumplingfish', rarity: 'common', note: '' },
      { name: 'Spotted Stingray', rarity: 'common', note: '' },
      { name: 'Yellow Peacock Bass', rarity: 'common', note: '' },
      { name: 'Shovelnose Catfish', rarity: 'common', note: '' },
      { name: 'Ligaka Guppy', rarity: 'common', note: '' },
      { name: 'Excavator Catfish', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'koza-eastern-marsh-ligaka', name: 'Eastern Marsh Ligaka', zone: 'Kozama\'uka', expansion: 'Dawntrail',
    coords: 'X:24, Y:32', weather: null, time: 'Any',
    baits: [],
    fish: [
      { name: 'Severum', rarity: 'common', note: '' },
      { name: 'Ligaka Blossom', rarity: 'common', note: '' },
      { name: 'Potglaze Stingray', rarity: 'common', note: '' },
      { name: 'Emberwisp', rarity: 'common', note: '' },
      { name: 'Ihuyka Colossoma', rarity: 'common', note: '' },
      { name: 'Torchtail', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'koza-western-marsh-ligaka', name: 'Western Marsh Ligaka', zone: 'Kozama\'uka', expansion: 'Dawntrail',
    coords: 'X:21, Y:33', weather: null, time: 'Any',
    baits: [],
    fish: [
      { name: 'Variegated Sisterscale', rarity: 'common', note: '' },
      { name: 'Kozama\'uka Characin', rarity: 'common', note: '' },
      { name: 'Charcoal Eel', rarity: 'common', note: '' },
      { name: 'Rainbow Pipira', rarity: 'common', note: '' },
      { name: 'Lau Lau', rarity: 'common', note: '' },
      { name: 'Ligaka Pirarucu', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'koza-marsh-ligaka-depths', name: 'Marsh Ligaka Depths', zone: 'Kozama\'uka', expansion: 'Dawntrail',
    coords: 'X:25, Y:31', weather: null, time: 'Any',
    baits: [],
    fish: [
      { name: 'Severum', rarity: 'common', note: '' },
      { name: 'Ihuyka Colossoma', rarity: 'common', note: '' },
      { name: 'Variegated Sisterscale', rarity: 'common', note: '' },
      { name: 'Charcoal Eel', rarity: 'common', note: '' },
      { name: 'Piraputanga', rarity: 'common', note: '' },
      { name: 'Purussaurus', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'yak-xd-aa-talat-tsoly', name: 'Xd\'aa Talat Tsoly', zone: 'Yak T\'el', expansion: 'Dawntrail',
    coords: 'X:13, Y:12', weather: null, time: 'Any',
    baits: [['Honeybee', '#e8c84e'], ['Versatile Lure', '#74e3dc'], ['Popper Lure', '#e87c4e'], ['Golden Stonefly Nymph', '#e8c84e']],
    fish: [
      { name: 'Shimmering Shadow', rarity: 'common', note: '' },
      { name: 'Ut\'ohmu Dawnfish', rarity: 'common', note: '' },
      { name: 'Iq Br\'aax Sailfin', rarity: 'common', note: '' },
      { name: 'Hunmu Ob', rarity: 'common', note: '' },
      { name: 'Deep Canopy', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'yak-yak-awak-tsoly', name: 'Yak Awak Tsoly', zone: 'Yak T\'el', expansion: 'Dawntrail',
    coords: 'X:19, Y:8', weather: null, time: 'Any',
    baits: [['Metal Spinner', '#8fb6d6'], ['Honeybee', '#e8c84e'], ['Versatile Lure', '#74e3dc'], ['Popper Lure', '#e87c4e']],
    fish: [
      { name: 'Shimmering Shadow', rarity: 'common', note: '' },
      { name: 'Ut\'ohmu Dawnfish', rarity: 'common', note: '' },
      { name: 'Apoda', rarity: 'common', note: '' },
      { name: 'Mirror Carp', rarity: 'common', note: '' },
      { name: 'Yak Awak Core', rarity: 'common', note: '' },
      { name: 'Awaksbane Apoda', rarity: 'common', note: '' },
      { name: 'Odorous Waterweed', rarity: 'common', note: '' },
      { name: 'Tsoly Tea Grass', rarity: 'common', note: '' },
      { name: 'Tsoly Sponge', rarity: 'common', note: '' },
      { name: 'Tsoly Sweetfish', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'yak-iq-rrax-tsoly', name: 'Iq Rrax Tsoly', zone: 'Yak T\'el', expansion: 'Dawntrail',
    coords: 'X:31, Y:6', weather: null, time: 'Any',
    baits: [['Honeybee', '#e8c84e'], ['Versatile Lure', '#74e3dc'], ['Popper Lure', '#e87c4e'], ['Golden Stonefly Nymph', '#e8c84e']],
    fish: [
      { name: 'Tsoly Mu', rarity: 'common', note: '' },
      { name: 'Iq Rrax Leaffish', rarity: 'common', note: '' },
      { name: 'Archmatron Angelfish', rarity: 'common', note: '' },
      { name: 'Yak T\'el Salamander', rarity: 'common', note: '' },
      { name: 'Shadowtongue', rarity: 'common', note: '' },
      { name: 'Iq Rrax Whelk', rarity: 'common', note: '' },
      { name: 'Desiccant Mollusk', rarity: 'common', note: '' },
      { name: 'Moss Sample', rarity: 'common', note: '' },
      { name: 'Iron Shadowtongue', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'yak-xobr-it-tsoly', name: 'Xobr\'it Tsoly', zone: 'Yak T\'el', expansion: 'Dawntrail',
    coords: 'X:33, Y:16', weather: null, time: 'Any',
    baits: [['Honeybee', '#e8c84e'], ['Versatile Lure', '#74e3dc'], ['Popper Lure', '#e87c4e'], ['Golden Stonefly Nymph', '#e8c84e']],
    fish: [
      { name: 'Cloud-eye Carp', rarity: 'legendary', note: '' },
      { name: 'Xobr\'it Lobster', rarity: 'common', note: '' },
      { name: 'Sunbright Axolotl', rarity: 'common', note: '' },
      { name: 'Horned Frog', rarity: 'common', note: '' },
      { name: 'Lotl-in-waiting', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'yak-ankledeep', name: 'Ankledeep', zone: 'Yak T\'el', expansion: 'Dawntrail',
    coords: 'X:8, Y:27', weather: null, time: 'Any',
    baits: [['Honeybee', '#e8c84e'], ['Versatile Lure', '#74e3dc'], ['Popper Lure', '#e87c4e'], ['Red Maggots', '#d65858']],
    fish: [
      { name: 'Mudfish', rarity: 'common', note: '' },
      { name: 'Turali Beaded Lizard', rarity: 'common', note: '' },
      { name: 'Yak T\'el Catfish', rarity: 'common', note: '' },
      { name: 'Ankledeep Catfish', rarity: 'common', note: '' },
      { name: 'Anklefish', rarity: 'common', note: '' },
      { name: 'Crystalfish', rarity: 'common', note: '' },
      { name: 'Thick-boned Fish', rarity: 'common', note: '' },
      { name: 'Smokeshell', rarity: 'common', note: '' },
      { name: 'Shin Snuffler', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'yak-cenote-moxutural', name: 'Cenote Moxutural', zone: 'Yak T\'el', expansion: 'Dawntrail',
    coords: 'X:21, Y:20', weather: null, time: 'Any',
    baits: [['Honeybee', '#e8c84e'], ['Versatile Lure', '#74e3dc'], ['Popper Lure', '#e87c4e'], ['Golden Stonefly Nymph', '#e8c84e']],
    fish: [
      { name: 'Mudfish', rarity: 'common', note: '' },
      { name: 'Yak T\'el Catfish', rarity: 'common', note: '' },
      { name: 'Checkered Cichlid', rarity: 'common', note: '' },
      { name: 'Moxutural Gar', rarity: 'common', note: '' },
      { name: 'Freakish Fish', rarity: 'common', note: '' },
      { name: 'Waterweed Fish', rarity: 'common', note: '' },
      { name: 'Freshwater Mudfish', rarity: 'common', note: '' },
      { name: 'Moxutural Greatgar', rarity: 'rare', note: '' },
    ],
  },
  {
    id: 'yak-cenote-jayunja', name: 'Cenote Jayunja', zone: 'Yak T\'el', expansion: 'Dawntrail',
    coords: 'X:19, Y:32', weather: null, time: 'Any',
    baits: [['Honeybee', '#e8c84e'], ['Versatile Lure', '#74e3dc'], ['Popper Lure', '#e87c4e'], ['Red Maggots', '#d65858']],
    fish: [
      { name: 'Mudfish', rarity: 'common', note: '' },
      { name: 'Yak T\'el Catfish', rarity: 'common', note: '' },
      { name: 'Variatus', rarity: 'common', note: '' },
      { name: 'Flawless Saucer', rarity: 'common', note: '' },
      { name: 'Welkin Catfish', rarity: 'common', note: '' },
      { name: 'Aether-infused Algae', rarity: 'common', note: '' },
      { name: 'Shellfish of Living Light', rarity: 'common', note: '' },
      { name: 'Meteorfish', rarity: 'common', note: '' },
      { name: 'Promising Shellfish', rarity: 'common', note: '' },
      { name: 'Moonmarking Saucer', rarity: 'rare', note: '' },
    ],
  },
  {
    id: 'yak-sapsweet-cenote', name: 'Sapsweet Cenote', zone: 'Yak T\'el', expansion: 'Dawntrail',
    coords: 'X:35, Y:32', weather: null, time: 'Any',
    baits: [['Honeybee', '#e8c84e'], ['Versatile Lure', '#74e3dc'], ['Popper Lure', '#e87c4e'], ['Red Maggots', '#d65858']],
    fish: [
      { name: 'Mudfish', rarity: 'common', note: '' },
      { name: 'Yak T\'el Catfish', rarity: 'common', note: '' },
      { name: 'Glittergill', rarity: 'common', note: '' },
      { name: 'Twig Catfish', rarity: 'common', note: '' },
      { name: 'Autarch\'s Supper', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'yak-bitterbark-cenote', name: 'Bitterbark Cenote', zone: 'Yak T\'el', expansion: 'Dawntrail',
    coords: 'X:25, Y:39', weather: null, time: 'Any',
    baits: [['Metal Spinner', '#8fb6d6'], ['Honeybee', '#e8c84e'], ['Versatile Lure', '#74e3dc'], ['Popper Lure', '#e87c4e']],
    fish: [
      { name: 'Mudfish', rarity: 'common', note: '' },
      { name: 'Yak T\'el Catfish', rarity: 'common', note: '' },
      { name: 'Blind Brotula', rarity: 'common', note: '' },
      { name: 'Yak T\'el Caiman', rarity: 'common', note: '' },
      { name: 'Cenote Oyster', rarity: 'common', note: '' },
      { name: 'Cexudross Fish', rarity: 'common', note: '' },
      { name: 'Bitterbark Caiman', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'yak-xty-iinbek-tsoly', name: 'Xty\'iinbek Tsoly', zone: 'Yak T\'el', expansion: 'Dawntrail',
    coords: 'X:37, Y:25', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Crimson Lugworm', '#d65858'], ['Ghost Nipper', '#8fb6d6'], ['Shucked Clam', '#c4b8a0']],
    fish: [
      { name: 'Timeworn Br\'aaxskin Map', rarity: 'common', note: '' },
      { name: 'Sharknose Goby', rarity: 'common', note: '' },
      { name: 'Yak T\'el Crab', rarity: 'common', note: '' },
      { name: 'Xty\'iinbek Sleeper', rarity: 'common', note: '' },
      { name: 'Chain Shark', rarity: 'common', note: '' },
      { name: 'Ut\'ohmu Tiika', rarity: 'common', note: '' },
      { name: 'Stardust Sleeper', rarity: 'legendary', note: '' },
    ],
  },
  {
    id: 'yak-western-iq-rrax-tsoly', name: 'Western Iq Rrax Tsoly', zone: 'Yak T\'el', expansion: 'Dawntrail',
    coords: 'X:28, Y:5', weather: null, time: 'Any',
    baits: [],
    fish: [
      { name: 'Timeworn Loboskin Map', rarity: 'common', note: '' },
      { name: 'Sunlit Prism', rarity: 'common', note: '' },
      { name: 'Fategazer', rarity: 'common', note: '' },
      { name: 'Frillfin Goby', rarity: 'common', note: '' },
      { name: 'Black Ibruq', rarity: 'common', note: '' },
      { name: 'Speckled Peacock Bass', rarity: 'common', note: '' },
      { name: 'Golden Characin', rarity: 'rare', note: '' },
    ],
  },
  {
    id: 'yak-eastern-iq-rrax-tsoly', name: 'Eastern Iq Rrax Tsoly', zone: 'Yak T\'el', expansion: 'Dawntrail',
    coords: 'X:35, Y:8', weather: null, time: 'Any',
    baits: [],
    fish: [
      { name: 'Timeworn Br\'aaxskin Map', rarity: 'common', note: '' },
      { name: 'Deadleaf Minnow', rarity: 'common', note: '' },
      { name: 'Glistening Discus', rarity: 'common', note: '' },
      { name: 'Lightning Eel', rarity: 'common', note: '' },
      { name: 'Longwhisker Lungfish', rarity: 'common', note: '' },
      { name: 'Minted Arowana', rarity: 'common', note: '' },
      { name: 'Br\'aaxfish', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'yak-iq-rrax-tsoly-depths', name: 'Iq Rrax Tsoly Depths', zone: 'Yak T\'el', expansion: 'Dawntrail',
    coords: 'X:31, Y:7', weather: null, time: 'Any',
    baits: [],
    fish: [
      { name: 'Frillfin Goby', rarity: 'common', note: '' },
      { name: 'Speckled Peacock Bass', rarity: 'common', note: '' },
      { name: 'Deadleaf Minnow', rarity: 'common', note: '' },
      { name: 'Lightning Eel', rarity: 'common', note: '' },
      { name: 'Iq Rrax Crab', rarity: 'common', note: '' },
      { name: 'Wivre Cod', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'solu-residential-sector', name: 'Residential Sector', zone: 'Solution Nine', expansion: 'Dawntrail',
    coords: 'X:6, Y:18', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Popper Lure', '#e87c4e'], ['Red Maggots', '#d65858']],
    fish: [
      { name: 'Custodian Carp', rarity: 'common', note: '' },
      { name: 'Mosaic Loach', rarity: 'common', note: '' },
      { name: 'Stickleback', rarity: 'common', note: '' },
      { name: 'Everkeep Yabby', rarity: 'common', note: '' },
      { name: 'Pixel Loach', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'shaa-niikwerepi', name: 'Niikwerepi', zone: 'Shaaloani', expansion: 'Dawntrail',
    coords: 'X:29, Y:7', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Popper Lure', '#e87c4e'], ['Red Maggots', '#d65858']],
    fish: [
      { name: 'Shaaloani Salmon', rarity: 'common', note: '' },
      { name: 'Niikwerepi Trout', rarity: 'common', note: '' },
      { name: 'Bonytail Chub', rarity: 'common', note: '' },
      { name: 'Pyariyoanaan Cichlid', rarity: 'common', note: '' },
      { name: 'Hwittayoanaan Cichlid', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'shaa-lake-toari', name: 'Lake Toari', zone: 'Shaaloani', expansion: 'Dawntrail',
    coords: 'X:31, Y:13', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Popper Lure', '#e87c4e'], ['Red Maggots', '#d65858']],
    fish: [
      { name: 'Toari Sucker', rarity: 'common', note: '' },
      { name: 'Turali Paddlefish', rarity: 'common', note: '' },
      { name: 'Trailtrout', rarity: 'common', note: '' },
      { name: 'Niikwerepi Trout', rarity: 'common', note: '' },
      { name: 'Bonytail Chub', rarity: 'common', note: '' },
      { name: 'Ttokatoa', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'shaa-westbound-zorgor', name: 'Westbound Zorgor', zone: 'Shaaloani', expansion: 'Dawntrail',
    coords: 'X:15, Y:38', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Cactuar Jig', '#74e3dc'], ['Dragonfly (Item)', '#74e3dc']],
    fish: [
      { name: 'Zorgor Scorpion', rarity: 'common', note: '' },
      { name: 'Cloudribbon', rarity: 'legendary', note: '' },
      { name: 'Vagrant Cascade', rarity: 'common', note: '' },
      { name: 'Zorgor Condor', rarity: 'common', note: '' },
      { name: 'Zorgor Core', rarity: 'common', note: '' },
      { name: 'Sunray Ray', rarity: 'common', note: '' },
      { name: 'Vagrant Keeper', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'shaa-eastbound-zorgor', name: 'Eastbound Zorgor', zone: 'Shaaloani', expansion: 'Dawntrail',
    coords: 'X:33, Y:38', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Cactuar Jig', '#74e3dc'], ['Dragonfly (Item)', '#74e3dc']],
    fish: [
      { name: 'Hellsnow Shark', rarity: 'common', note: '' },
      { name: 'Azure Glider', rarity: 'common', note: '' },
      { name: 'Cloud Wasp', rarity: 'legendary', note: '' },
      { name: 'Raging Hanuhead', rarity: 'common', note: '' },
      { name: 'Zorgor Core', rarity: 'common', note: '' },
      { name: 'Cloudsail', rarity: 'legendary', note: '' },
      { name: 'Azure Diver', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'shaa-northern-lake-toari', name: 'Northern Lake Toari', zone: 'Shaaloani', expansion: 'Dawntrail',
    coords: 'X:32, Y:11', weather: null, time: 'Any',
    baits: [],
    fish: [
      { name: 'Timeworn Br\'aaxskin Map', rarity: 'common', note: '' },
      { name: 'Warmouth', rarity: 'common', note: '' },
      { name: 'Longnose Gar', rarity: 'common', note: '' },
      { name: 'Niikwerepi Bass', rarity: 'common', note: '' },
      { name: 'Sauger', rarity: 'common', note: '' },
      { name: 'Shaaloani Goby', rarity: 'common', note: '' },
      { name: 'Midnight Carp', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'heri-outskirts-shallows', name: 'Outskirts Shallows', zone: 'Heritage Found', expansion: 'Dawntrail',
    coords: 'X:19, Y:8', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Popper Lure', '#e87c4e'], ['Red Maggots', '#d65858']],
    fish: [
      { name: 'Timeworn Br\'aaxskin Map', rarity: 'common', note: '' },
      { name: 'Tiger Muskellunge', rarity: 'common', note: '' },
      { name: 'Outskirts Sniffer', rarity: 'common', note: '' },
      { name: 'Heritage Loach', rarity: 'common', note: '' },
      { name: 'Pumpkin Perch', rarity: 'common', note: '' },
      { name: 'Sprouting Perch', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'heri-the-driftdowns', name: 'The Driftdowns', zone: 'Heritage Found', expansion: 'Dawntrail',
    coords: 'X:13, Y:17', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Popper Lure', '#e87c4e'], ['Red Maggots', '#d65858']],
    fish: [
      { name: 'Timeworn Br\'aaxskin Map', rarity: 'common', note: '' },
      { name: 'Outskirts Sniffer', rarity: 'common', note: '' },
      { name: 'Heritage Loach', rarity: 'common', note: '' },
      { name: 'Driftdowns Trout', rarity: 'common', note: '' },
      { name: 'Moon Croppie', rarity: 'common', note: '' },
      { name: 'Thunderswift Trout', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'heri-crackling-canyons', name: 'Crackling Canyons', zone: 'Heritage Found', expansion: 'Dawntrail',
    coords: 'X:21, Y:32', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Popper Lure', '#e87c4e'], ['Red Maggots', '#d65858']],
    fish: [
      { name: 'Timeworn Br\'aaxskin Map', rarity: 'common', note: '' },
      { name: 'Thundering Redbelly', rarity: 'common', note: '' },
      { name: 'Electrobetta', rarity: 'common', note: '' },
      { name: 'Crackling Flounder', rarity: 'common', note: '' },
      { name: 'Yyasulani Bowfin', rarity: 'common', note: '' },
      { name: 'Thunderous Flounder', rarity: 'common', note: '' },
      { name: 'Goldentail', rarity: 'rare', note: '' },
    ],
  },
  {
    id: 'heri-alexandrian-ruins', name: 'Alexandrian Ruins', zone: 'Heritage Found', expansion: 'Dawntrail',
    coords: 'X:6, Y:34', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Popper Lure', '#e87c4e'], ['Red Maggots', '#d65858']],
    fish: [
      { name: 'Timeworn Br\'aaxskin Map', rarity: 'common', note: '' },
      { name: 'Goldgrouper', rarity: 'common', note: '' },
      { name: 'Thundering Redbelly', rarity: 'common', note: '' },
      { name: 'Electrobetta', rarity: 'common', note: '' },
      { name: 'Yyasulani Bowfin', rarity: 'common', note: '' },
      { name: 'Heirloom Goldgrouper', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'livi-the-knowable', name: 'The Knowable', zone: 'Living Memory', expansion: 'Dawntrail',
    coords: 'X:7, Y:14', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Popper Lure', '#e87c4e'], ['Red Maggots', '#d65858']],
    fish: [
      { name: 'Knight Goby', rarity: 'common', note: '' },
      { name: 'Rosebud Frog', rarity: 'common', note: '' },
      { name: 'Harlequin Lancer', rarity: 'common', note: '' },
      { name: 'Windspath Eel', rarity: 'common', note: '' },
      { name: 'Harlequin Queen', rarity: 'rare', note: '' },
    ],
  },
  {
    id: 'livi-mu-springs-eternal', name: 'Mu Springs Eternal', zone: 'Living Memory', expansion: 'Dawntrail',
    coords: 'X:12, Y:11', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Popper Lure', '#e87c4e'], ['Red Maggots', '#d65858']],
    fish: [
      { name: 'Cleyran Carp', rarity: 'common', note: '' },
      { name: 'Knight Goby', rarity: 'common', note: '' },
      { name: 'Rosebud Frog', rarity: 'common', note: '' },
      { name: 'Giant Snakehead', rarity: 'rare', note: '' },
      { name: 'Gigagiant Snakehead', rarity: 'rare', note: '' },
      { name: 'Timeworn Gargantuaskin Map', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'livi-leynode-aero', name: 'Leynode Aero', zone: 'Living Memory', expansion: 'Dawntrail',
    coords: 'X:16, Y:13', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Popper Lure', '#e87c4e'], ['Red Maggots', '#d65858']],
    fish: [
      { name: 'Neo Arowana', rarity: 'common', note: '' },
      { name: 'Knight Goby', rarity: 'common', note: '' },
      { name: 'Datnioides', rarity: 'common', note: '' },
      { name: 'Rosebud Frog', rarity: 'common', note: '' },
      { name: 'Datnioides Aeroplanos', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'livi-canal-town-south', name: 'Canal Town South', zone: 'Living Memory', expansion: 'Dawntrail',
    coords: 'X:14, Y:34', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Ghost Nipper', '#8fb6d6'], ['Shucked Clam', '#c4b8a0']],
    fish: [
      { name: 'Canal Drum', rarity: 'common', note: '' },
      { name: 'Iris Wrasse', rarity: 'common', note: '' },
      { name: 'Hydro Louvar', rarity: 'common', note: '' },
      { name: 'Canal Bream', rarity: 'common', note: '' },
      { name: 'Butterfly Ray', rarity: 'common', note: '' },
      { name: 'Gondola Louvar', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'livi-canal-town-north', name: 'Canal Town North', zone: 'Living Memory', expansion: 'Dawntrail',
    coords: 'X:9, Y:28', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Ghost Nipper', '#8fb6d6'], ['Shucked Clam', '#c4b8a0']],
    fish: [
      { name: 'Devotion Clam', rarity: 'common', note: '' },
      { name: 'Forgotten One', rarity: 'common', note: '' },
      { name: 'Copper Shark', rarity: 'common', note: '' },
      { name: 'Iris Wrasse', rarity: 'common', note: '' },
      { name: 'Canal Bream', rarity: 'common', note: '' },
      { name: 'Shined Copper Shark', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'livi-proto-alexandria', name: 'Proto Alexandria', zone: 'Living Memory', expansion: 'Dawntrail',
    coords: 'X:38, Y:31', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Popper Lure', '#e87c4e'], ['Red Maggots', '#d65858']],
    fish: [
      { name: 'Golden Day', rarity: 'rare', note: '' },
      { name: 'Ultimoat Carp', rarity: 'common', note: '' },
      { name: 'Scarlet Queen', rarity: 'rare', note: '' },
      { name: 'Starglass Gibel', rarity: 'legendary', note: '' },
      { name: 'Esperance Carp', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'old-scholar-s-harbor', name: 'Scholar\'s Harbor', zone: 'Old Sharlayan', expansion: 'Endwalker',
    coords: 'X:11, Y:15', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Mackerel Strip', '#7bbfb8'], ['Shrimp Ball', '#e8b090']],
    fish: [
      { name: 'Northern Herring', rarity: 'common', note: '' },
      { name: 'Cobalt Chromis', rarity: 'common', note: '' },
      { name: 'Dog-faced Puffer', rarity: 'common', note: '' },
      { name: 'Guitarfish', rarity: 'common', note: '' },
      { name: 'Pecten', rarity: 'common', note: '' },
      { name: 'Aetherolectric Guitarfish', rarity: 'rare', note: '' },
    ],
  },
  {
    id: 'old-oinops', name: 'Oinops', zone: 'Old Sharlayan', expansion: 'Endwalker',
    coords: 'X:11, Y:8', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Gold Salmon Roe', '#e8c84e'], ['Mayfly', '#74e3dc'], ['Leech (Bait)', '#b07060']],
    fish: [
      { name: 'Academician', rarity: 'rare', note: '' },
      { name: 'Astacus', rarity: 'common', note: '' },
      { name: 'Peacock Bass', rarity: 'common', note: '' },
      { name: 'Swordspine Snook', rarity: 'rare', note: '' },
      { name: 'Greatsword Snook', rarity: 'rare', note: '' },
    ],
  },
  {
    id: 'old-reflecting-pool', name: 'Reflecting Pool', zone: 'Old Sharlayan', expansion: 'Endwalker',
    coords: 'X:7.7, Y:10.7', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Sky Spoon Lure', '#74e3dc'], ['Gold Salmon Roe', '#e8c84e'], ['Mayfly', '#74e3dc']],
    fish: [
      { name: 'Astacus', rarity: 'common', note: '' },
      { name: 'Ponderer', rarity: 'common', note: '' },
      { name: 'Tidal Dahlia', rarity: 'common', note: '' },
      { name: 'Catastrophizer', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'laby-unmoved-source-alpha', name: 'Unmoved Source Alpha', zone: 'Labyrinthos', expansion: 'Endwalker',
    coords: 'X:17.7, Y:5.3', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Sky Spoon Lure', '#74e3dc'], ['Gold Salmon Roe', '#e8c84e'], ['Mayfly', '#74e3dc']],
    fish: [
      { name: 'Butterfly Fry', rarity: 'common', note: '' },
      { name: 'Giant Aetherlouse', rarity: 'rare', note: '' },
      { name: 'Fat Snook', rarity: 'common', note: '' },
      { name: 'Tessera', rarity: 'common', note: '' },
      { name: 'Topminnow', rarity: 'common', note: '' },
      { name: 'Jumbo Snook', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'laby-the-mover-alpha', name: 'The Mover Alpha', zone: 'Labyrinthos', expansion: 'Endwalker',
    coords: 'X:18, Y:9', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Sky Spoon Lure', '#74e3dc'], ['Gold Salmon Roe', '#e8c84e'], ['Mayfly', '#74e3dc']],
    fish: [
      { name: 'Xenocypris', rarity: 'common', note: '' },
      { name: 'Butterfly Fry', rarity: 'common', note: '' },
      { name: 'Greengill Salmon', rarity: 'common', note: '' },
      { name: 'Mesonauta', rarity: 'common', note: '' },
      { name: 'Prochilodus Luminosus', rarity: 'common', note: '' },
      { name: 'Mossgill Salmon', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'laby-unmoved-source-beta', name: 'Unmoved Source Beta', zone: 'Labyrinthos', expansion: 'Endwalker',
    coords: 'X:32.3, Y:8.6', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Sky Spoon Lure', '#74e3dc'], ['Gold Salmon Roe', '#e8c84e'], ['Mayfly', '#74e3dc']],
    fish: [
      { name: 'Xenocypris', rarity: 'common', note: '' },
      { name: 'Butterfly Fry', rarity: 'common', note: '' },
      { name: 'Raiamas', rarity: 'common', note: '' },
      { name: 'Red Bowfin', rarity: 'common', note: '' },
      { name: 'Swampsucker Bowfin', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'laby-the-mover-beta', name: 'The Mover Beta', zone: 'Labyrinthos', expansion: 'Endwalker',
    coords: 'X:28, Y:15', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Sky Spoon Lure', '#74e3dc'], ['Gold Salmon Roe', '#e8c84e'], ['Mayfly', '#74e3dc']],
    fish: [
      { name: 'Blowgun', rarity: 'common', note: '' },
      { name: 'Xenocypris', rarity: 'common', note: '' },
      { name: 'Butterfly Fry', rarity: 'common', note: '' },
      { name: 'Darksteel Knifefish', rarity: 'common', note: '' },
      { name: 'Macrobrachium Lar', rarity: 'common', note: '' },
      { name: 'The Fury\'s Aegis', rarity: 'common', note: '' },
      { name: 'Onyx Knifefish', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'laby-deepmoat', name: 'Deepmoat', zone: 'Labyrinthos', expansion: 'Endwalker',
    coords: 'X:20, Y:16', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Sky Spoon Lure', '#74e3dc'], ['Gold Salmon Roe', '#e8c84e'], ['Mayfly', '#74e3dc']],
    fish: [
      { name: 'Xenocypris', rarity: 'common', note: '' },
      { name: 'Butterfly Fry', rarity: 'common', note: '' },
      { name: 'Labyrinthos Tilapia', rarity: 'common', note: '' },
      { name: 'Astacus Aetherius', rarity: 'common', note: '' },
      { name: 'Circuit Tilapia', rarity: 'common', note: '' },
      { name: 'Hyphalosaurus', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'radz-meghaduta', name: 'Meghaduta', zone: 'Radz-at-Han', expansion: 'Endwalker',
    coords: 'X:5, Y:11', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Sky Spoon Lure', '#74e3dc'], ['Gold Salmon Roe', '#e8c84e'], ['Mayfly', '#74e3dc']],
    fish: [
      { name: 'Silver Characin', rarity: 'common', note: '' },
      { name: 'Longear Sunfish', rarity: 'rare', note: '' },
      { name: 'Seema Duta', rarity: 'common', note: '' },
      { name: 'Trunkblessed', rarity: 'common', note: '' },
      { name: 'Earful', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'thav-yedlihmad', name: 'Yedlihmad', zone: 'Thavnair', expansion: 'Endwalker',
    coords: 'X:27, Y:35', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Mackerel Strip', '#7bbfb8'], ['Shrimp Ball', '#e8b090']],
    fish: [
      { name: 'Thavnairian Goby', rarity: 'common', note: '' },
      { name: 'Qeyiq Sole', rarity: 'common', note: '' },
      { name: 'Gwl Crab', rarity: 'common', note: '' },
      { name: 'Pantherscale Grouper', rarity: 'common', note: '' },
      { name: 'Lale Crab', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'thav-the-thavnairian-coast', name: 'The Thavnairian Coast', zone: 'Thavnair', expansion: 'Endwalker',
    coords: 'X:9, Y:33', weather: null, time: 'Any',
    baits: [['Metal Spinner', '#8fb6d6'], ['Versatile Lure', '#74e3dc'], ['Mackerel Strip', '#7bbfb8'], ['Shrimp Ball', '#e8b090']],
    fish: [
      { name: 'Thavnairian Goby', rarity: 'common', note: '' },
      { name: 'Qeyiq Sole', rarity: 'common', note: '' },
      { name: 'Fate\'s Design', rarity: 'common', note: '' },
      { name: 'Paksa Fish', rarity: 'common', note: '' },
      { name: 'Shadowdart Sardine', rarity: 'common', note: '' },
      { name: 'Chalky Coral', rarity: 'common', note: '' },
      { name: 'Jhinga', rarity: 'common', note: '' },
      { name: 'Durdina Fish', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'thav-the-great-runoff', name: 'The Great Runoff', zone: 'Thavnair', expansion: 'Endwalker',
    coords: 'X:10.2, Y:22.6', weather: null, time: 'Any',
    baits: [['Metal Spinner', '#8fb6d6'], ['Versatile Lure', '#74e3dc'], ['Shrimp Ball', '#e8b090']],
    fish: [
      { name: 'Thavnairian Goby', rarity: 'common', note: '' },
      { name: 'Garjana Wrasse', rarity: 'common', note: '' },
      { name: 'Qeyiq Sole', rarity: 'common', note: '' },
      { name: 'Golden Barramundi', rarity: 'rare', note: '' },
      { name: 'Vidyutvat Wrasse', rarity: 'common', note: '' },
      { name: 'Sarikuyruk', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'thav-giantsgall-grounds', name: 'Giantsgall Grounds', zone: 'Thavnair', expansion: 'Endwalker',
    coords: 'X:20.7, Y:7.9', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Sky Spoon Lure', '#74e3dc'], ['Gold Salmon Roe', '#e8c84e'], ['Mayfly', '#74e3dc']],
    fish: [
      { name: 'Bronze Pipira', rarity: 'common', note: '' },
      { name: 'Kadjaya\'s Castaway', rarity: 'common', note: '' },
      { name: 'Bluegill', rarity: 'common', note: '' },
      { name: 'Marid Frog', rarity: 'common', note: '' },
      { name: 'Hippo Frog', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'thav-the-wakeful-torana', name: 'The Wakeful Torana', zone: 'Thavnair', expansion: 'Endwalker',
    coords: 'X:30, Y:10', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Gold Salmon Roe', '#e8c84e'], ['Mayfly', '#74e3dc'], ['Leech (Bait)', '#b07060']],
    fish: [
      { name: 'Green Swordtail', rarity: 'common', note: '' },
      { name: 'Red Drum', rarity: 'common', note: '' },
      { name: 'Ksirapayin', rarity: 'common', note: '' },
      { name: 'Wakeful Watcher', rarity: 'common', note: '' },
      { name: 'Wakeful Warden', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'thav-ksiroda', name: 'Ksiroda', zone: 'Thavnair', expansion: 'Endwalker',
    coords: 'X:30, Y:20', weather: null, time: 'Any',
    baits: [['Metal Spinner', '#8fb6d6'], ['Versatile Lure', '#74e3dc'], ['Sky Spoon Lure', '#74e3dc'], ['Gold Salmon Roe', '#e8c84e']],
    fish: [
      { name: 'Green Swordtail', rarity: 'common', note: '' },
      { name: 'Bicuda', rarity: 'common', note: '' },
      { name: 'Forgeflame', rarity: 'common', note: '' },
      { name: 'Ksirapayin', rarity: 'common', note: '' },
      { name: 'Seedtoad', rarity: 'common', note: '' },
      { name: 'Bigcuda', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'thav-pavana-s-remorse', name: 'Pavana\'s Remorse', zone: 'Thavnair', expansion: 'Endwalker',
    coords: 'X:23.8, Y:14.2', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Gold Salmon Roe', '#e8c84e'], ['Mayfly', '#74e3dc'], ['Leech (Bait)', '#b07060']],
    fish: [
      { name: 'Green Swordtail', rarity: 'common', note: '' },
      { name: 'Banana Eel', rarity: 'common', note: '' },
      { name: 'Half-moon Betta', rarity: 'common', note: '' },
      { name: 'Radzbalik', rarity: 'common', note: '' },
      { name: 'Browned Banana Eel', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'thav-the-perfumed-tides', name: 'The Perfumed Tides', zone: 'Thavnair', expansion: 'Endwalker',
    coords: 'X:6, Y:8', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Mackerel Strip', '#7bbfb8'], ['Shrimp Ball', '#e8b090']],
    fish: [
      { name: 'Mackerel Strip', rarity: 'common', note: '' },
      { name: 'Basilosaurus', rarity: 'common', note: '' },
      { name: 'Fiery Goby', rarity: 'common', note: '' },
      { name: 'Narunnairian Octopus', rarity: 'common', note: '' },
      { name: 'Puff-paya', rarity: 'common', note: '' },
      { name: 'Roosterfish', rarity: 'common', note: '' },
      { name: 'Thavnairian Calamari', rarity: 'common', note: '' },
      { name: 'Basilosaurus Rex', rarity: 'common', note: '' },
      { name: 'Gharlichthys', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'thav-southern-akyaali', name: 'Southern Akyaali', zone: 'Thavnair', expansion: 'Endwalker',
    coords: 'X:14, Y:37', weather: null, time: 'Any',
    baits: [],
    fish: [
      { name: 'Spiny King Crab', rarity: 'rare', note: '' },
      { name: 'Giantsgall Jaw', rarity: 'rare', note: '' },
      { name: 'Gilled Topknot', rarity: 'common', note: '' },
      { name: 'Purusa Fish', rarity: 'common', note: '' },
      { name: 'Thavnairian Cucumber', rarity: 'common', note: '' },
      { name: 'Thavnairian Eel', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'thav-western-akyaali', name: 'Western Akyaali', zone: 'Thavnair', expansion: 'Endwalker',
    coords: 'X:8.2, Y:32.7', weather: null, time: 'Any',
    baits: [],
    fish: [
      { name: 'Timeworn Saigaskin Map', rarity: 'common', note: '' },
      { name: 'Akyaali Sardine', rarity: 'common', note: '' },
      { name: 'Blue Marlin', rarity: 'common', note: '' },
      { name: 'Hedonfish', rarity: 'common', note: '' },
      { name: 'Mayavahana', rarity: 'common', note: '' },
      { name: 'Satrap Trapfish', rarity: 'common', note: '' },
      { name: 'Spicy Pickle', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'thav-southern-great-runoff', name: 'Southern Great Runoff', zone: 'Thavnair', expansion: 'Endwalker',
    coords: 'X:4, Y:28', weather: null, time: 'Any',
    baits: [],
    fish: [
      { name: 'Shallows Cod', rarity: 'common', note: '' },
      { name: 'Satrap\'s Whisper', rarity: 'common', note: '' },
      { name: 'Daemir\'s Alloy', rarity: 'common', note: '' },
      { name: 'Meyhane Reveler', rarity: 'common', note: '' },
      { name: 'Rasa Fish', rarity: 'common', note: '' },
      { name: 'Dusky Shark', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'thav-the-font-of-maya', name: 'The Font of Maya', zone: 'Thavnair', expansion: 'Endwalker',
    coords: 'X:24.5, Y:24.4', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Sky Spoon Lure', '#74e3dc'], ['Gold Salmon Roe', '#e8c84e'], ['Mayfly', '#74e3dc']],
    fish: [
      { name: 'Green Swordtail', rarity: 'common', note: '' },
      { name: 'Flowerhorn', rarity: 'common', note: '' },
      { name: 'Handy Hamsa', rarity: 'common', note: '' },
      { name: 'Radzbalik', rarity: 'common', note: '' },
      { name: 'Thavnairian Caiman', rarity: 'common', note: '' },
      { name: 'Mayashell', rarity: 'common', note: '' },
      { name: 'Mayaman', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'thav-outer-akyaali', name: 'Outer Akyaali', zone: 'Thavnair', expansion: 'Endwalker',
    coords: 'X:6, Y:36', weather: null, time: 'Any',
    baits: [],
    fish: [
      { name: 'Shallows Cod', rarity: 'common', note: '' },
      { name: 'Gilled Topknot', rarity: 'common', note: '' },
      { name: 'Hedonfish', rarity: 'common', note: '' },
      { name: 'Tebqeyiq Smelt', rarity: 'common', note: '' },
      { name: 'Meyhane Reveler', rarity: 'common', note: '' },
      { name: 'Xiphactinus', rarity: 'common', note: '' },
      { name: 'Dusky Shark', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'garl-the-eblan-thaw', name: 'The Eblan Thaw', zone: 'Garlemald', expansion: 'Endwalker',
    coords: 'X:11, Y:30.7', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Gold Salmon Roe', '#e8c84e'], ['Mayfly', '#74e3dc'], ['Leech (Bait)', '#b07060']],
    fish: [
      { name: 'Icepike', rarity: 'common', note: '' },
      { name: 'Garlean Clam', rarity: 'common', note: '' },
      { name: 'Eblan Trout', rarity: 'common', note: '' },
      { name: 'Animulus', rarity: 'common', note: '' },
      { name: 'Cerule Core', rarity: 'common', note: '' },
      { name: 'Rimepike', rarity: 'common', note: '' },
      { name: 'Snowy Parexus', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'garl-the-stainless-course', name: 'The Stainless Course', zone: 'Garlemald', expansion: 'Endwalker',
    coords: 'X:23, Y:6', weather: null, time: 'Any',
    baits: [['Metal Spinner', '#8fb6d6'], ['Versatile Lure', '#74e3dc'], ['Sky Spoon Lure', '#74e3dc'], ['Gold Salmon Roe', '#e8c84e']],
    fish: [
      { name: 'Garlean Clam', rarity: 'common', note: '' },
      { name: 'Eblan Trout', rarity: 'common', note: '' },
      { name: 'Dark Crown', rarity: 'common', note: '' },
      { name: 'Bluetail', rarity: 'common', note: '' },
      { name: 'Imperial Pleco', rarity: 'common', note: '' },
      { name: 'Sovereign Shadow', rarity: 'common', note: '' },
      { name: 'Kitty Herring', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'mare-greatest-endsvale', name: 'Greatest Endsvale', zone: 'Mare Lamentorum', expansion: 'Endwalker',
    coords: 'X:32, Y:10', weather: null, time: 'Any',
    baits: [['Metal Spinner', '#8fb6d6'], ['Versatile Lure', '#74e3dc'], ['Sky Spoon Lure', '#74e3dc'], ['Gold Salmon Roe', '#e8c84e']],
    fish: [
      { name: 'Lunar Cichlid', rarity: 'common', note: '' },
      { name: 'Replipirarucu', rarity: 'common', note: '' },
      { name: 'Star-blue Guppy', rarity: 'legendary', note: '' },
      { name: 'Teareye', rarity: 'common', note: '' },
      { name: 'Disappirarucu', rarity: 'common', note: '' },
      { name: 'Ossicula', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'mare-the-chlorophospond', name: 'The Chlorophospond', zone: 'Mare Lamentorum', expansion: 'Endwalker',
    coords: 'X:30, Y:32', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Grey Worm', '#74e3dc'], ['Chimera Worm', '#74e3dc']],
    fish: [
      { name: 'Lunar Deathworm', rarity: 'common', note: '' },
      { name: 'Calicia', rarity: 'common', note: '' },
      { name: 'Feverfish', rarity: 'common', note: '' },
      { name: 'Protomyke 987', rarity: 'common', note: '' },
      { name: 'Chlorophos Deathworm', rarity: 'common', note: '' },
      { name: 'Lopoceras Elegans', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'mare-the-frozen-fissure', name: 'The Frozen Fissure', zone: 'Mare Lamentorum', expansion: 'Endwalker',
    coords: 'X:22, Y:31', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Grey Worm', '#74e3dc'], ['Chimera Worm', '#74e3dc']],
    fish: [
      { name: 'Lunar Lamenter', rarity: 'common', note: '' },
      { name: 'Calicia', rarity: 'common', note: '' },
      { name: 'Feverfish', rarity: 'common', note: '' },
      { name: 'Fleeting Brand', rarity: 'common', note: '' },
      { name: 'Regotoise', rarity: 'common', note: '' },
      { name: 'Frozen Regotoise', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'ulti-apohelos-18', name: 'Apohelos 18-α', zone: 'Ultima Thule', expansion: 'Endwalker',
    coords: 'X:7, Y:22.5', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Grey Worm', '#74e3dc'], ['Chimera Worm', '#74e3dc']],
    fish: [
      { name: 'Timeworn Kumbhiraskin Map', rarity: 'common', note: '' },
      { name: 'Dragonscale', rarity: 'common', note: '' },
      { name: 'Eehs Forhnesh', rarity: 'common', note: '' },
      { name: 'Star Eater', rarity: 'legendary', note: '' },
      { name: 'Superstring', rarity: 'common', note: '' },
      { name: 'Ypupîara', rarity: 'common', note: '' },
      { name: 'Eehs Fan', rarity: 'common', note: '' },
      { name: 'Stargilt Lobster', rarity: 'legendary', note: '' },
    ],
  },
  {
    id: 'ulti-the-wellspring-of-regret', name: 'The Wellspring of Regret', zone: 'Ultima Thule', expansion: 'Endwalker',
    coords: 'X:14.4, Y:11.1', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Sky Spoon Lure', '#74e3dc'], ['Gold Salmon Roe', '#e8c84e'], ['Mayfly', '#74e3dc']],
    fish: [
      { name: 'Aoide', rarity: 'common', note: '' },
      { name: 'Comet Tail', rarity: 'legendary', note: '' },
      { name: 'Katoptron', rarity: 'common', note: '' },
      { name: 'Protoflesh', rarity: 'common', note: '' },
      { name: 'Starscryer', rarity: 'legendary', note: '' },
      { name: 'Wildlife Sample', rarity: 'common', note: '' },
      { name: 'Soggy Alien Kelp', rarity: 'common', note: '' },
      { name: 'Stellar Herring', rarity: 'common', note: '' },
      { name: 'Methane Puffer', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'ulti-abode-of-the-ea', name: 'Abode of the Ea', zone: 'Ultima Thule', expansion: 'Endwalker',
    coords: 'X:22, Y:8', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Sky Spoon Lure', '#74e3dc'], ['Gold Salmon Roe', '#e8c84e'], ['Mayfly', '#74e3dc']],
    fish: [
      { name: 'Katoptron', rarity: 'common', note: '' },
      { name: 'Protoflesh', rarity: 'common', note: '' },
      { name: 'Wandering Starscale', rarity: 'legendary', note: '' },
      { name: 'Nondescript Fish', rarity: 'common', note: '' },
      { name: 'Meteoric Bonito', rarity: 'common', note: '' },
      { name: 'Sticky Fingers', rarity: 'common', note: '' },
      { name: 'Starscale Ephemeris', rarity: 'legendary', note: '' },
    ],
  },
  {
    id: 'ulti-limne-18', name: 'Limne 18', zone: 'Ultima Thule', expansion: 'Endwalker',
    coords: 'X:7, Y:35', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Stardust', '#74e3dc'], ['Panic Jig', '#74e3dc']],
    fish: [
      { name: 'Timeworn Kumbhiraskin Map', rarity: 'common', note: '' },
      { name: 'Stardust', rarity: 'legendary', note: '' },
      { name: 'Alien Mertone', rarity: 'common', note: '' },
      { name: 'Class Twenty-four', rarity: 'common', note: '' },
      { name: 'Monster Carrot', rarity: 'common', note: '' },
      { name: 'Sophos Deka-okto', rarity: 'common', note: '' },
      { name: 'Terrifyingway', rarity: 'common', note: '' },
      { name: 'Unidentified Flying Biomass II', rarity: 'common', note: '' },
      { name: 'Wormhole Worm', rarity: 'common', note: '' },
      { name: 'Forbiddingway', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'ulti-limne-3', name: 'Limne 3-α', zone: 'Ultima Thule', expansion: 'Endwalker',
    coords: 'X:36, Y:9', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Stardust', '#74e3dc'], ['Panic Jig', '#74e3dc']],
    fish: [
      { name: 'Timeworn Kumbhiraskin Map', rarity: 'common', note: '' },
      { name: 'Stardust', rarity: 'legendary', note: '' },
      { name: 'Alyketos', rarity: 'common', note: '' },
      { name: 'Argonaut', rarity: 'common', note: '' },
      { name: 'Echinos', rarity: 'common', note: '' },
      { name: 'Space Bishop', rarity: 'common', note: '' },
      { name: 'Triaina', rarity: 'common', note: '' },
      { name: 'Unidentified Flying Biomass II', rarity: 'common', note: '' },
      { name: 'Wormhole Worm', rarity: 'common', note: '' },
      { name: 'Argonauta argo', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'elys-elysian-fields', name: 'Elysian Fields', zone: 'Elysion', expansion: 'Endwalker',
    coords: 'X:6.3, Y:6.6', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Gold Salmon Roe', '#e8c84e'], ['Mayfly', '#74e3dc']],
    fish: [
      { name: 'Comet Tail', rarity: 'legendary', note: '' },
      { name: 'Protoflesh', rarity: 'common', note: '' },
      { name: 'Chemically Rich Fish', rarity: 'common', note: '' },
      { name: 'Fresh Seaweed', rarity: 'common', note: '' },
      { name: 'Chromatic Fish', rarity: 'common', note: '' },
      { name: 'Karellian Fishy Fish', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'elys-elysian-seas', name: 'Elysian Seas α', zone: 'Elysion', expansion: 'Endwalker',
    coords: 'X:6, Y:5', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Gold Salmon Roe', '#e8c84e'], ['Mayfly', '#74e3dc']],
    fish: [
      { name: 'Katoptron', rarity: 'common', note: '' },
      { name: 'Protoflesh', rarity: 'common', note: '' },
      { name: 'Elysian Nudibranch', rarity: 'common', note: '' },
      { name: 'Saltwater Fish', rarity: 'common', note: '' },
      { name: 'Supremest Crustacean', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'elys-elysian-playgrounds', name: 'Elysian Playgrounds α', zone: 'Elysion', expansion: 'Endwalker',
    coords: 'X:5, Y:6', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Gold Salmon Roe', '#e8c84e'], ['Mayfly', '#74e3dc']],
    fish: [
      { name: 'Protoflesh', rarity: 'common', note: '' },
      { name: 'Wandering Starscale', rarity: 'legendary', note: '' },
      { name: 'Astral Algae', rarity: 'common', note: '' },
      { name: 'Paraichthyoid', rarity: 'common', note: '' },
      { name: 'Babycray', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'elpi-rumination-s-ramble', name: 'Rumination\'s Ramble', zone: 'Elpis', expansion: 'Endwalker',
    coords: 'X:11, Y:19', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Sky Spoon Lure', '#74e3dc'], ['Gold Salmon Roe', '#e8c84e'], ['Mayfly', '#74e3dc']],
    fish: [
      { name: 'Iribainion', rarity: 'common', note: '' },
      { name: 'Isle Skipper', rarity: 'common', note: '' },
      { name: 'Mangar', rarity: 'common', note: '' },
      { name: 'Albino Loach', rarity: 'common', note: '' },
      { name: 'Golden Shiner', rarity: 'rare', note: '' },
      { name: 'Planetes', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'elpi-the-lower-hungering-gardens', name: 'The Lower Hungering Gardens', zone: 'Elpis', expansion: 'Endwalker',
    coords: 'X:25, Y:10', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Sky Spoon Lure', '#74e3dc'], ['Gold Salmon Roe', '#e8c84e'], ['Mayfly', '#74e3dc']],
    fish: [
      { name: 'Iribainion', rarity: 'common', note: '' },
      { name: 'Isle Skipper', rarity: 'common', note: '' },
      { name: 'Dermogenys', rarity: 'common', note: '' },
      { name: 'Colossoma', rarity: 'common', note: '' },
      { name: 'Phyllinos', rarity: 'common', note: '' },
      { name: 'Gilt Dermogenys', rarity: 'common', note: '' },
    ],
  },
  {
    id: 'elpi-lethe', name: 'Lethe', zone: 'Elpis', expansion: 'Endwalker',
    coords: 'X:33, Y:15', weather: null, time: 'Any',
    baits: [['Versatile Lure', '#74e3dc'], ['Sky Spoon Lure', '#74e3dc'], ['Gold Salmon Roe', '#e8c84e'], ['Mayfly', '#74e3dc']],
    fish: [
      { name: 'Iribainion', rarity: 'common', note: '' },
      { name: 'Isle Skipper', rarity: 'common', note: '' },
      { name: 'Smaragdos', rarity: 'common', note: '' },
      { name: 'Antheia', rarity: 'common', note: '' },
      { name: 'Timeworn Ophiotauroskin Map', rarity: 'common', note: '' },
      { name: 'Antheian Dahlia', rarity: 'common', note: '' },
      { name: 'Furcacauda', rarity: 'common', note: '' },
    ],
  }
];

export const EXPANSIONS = [
  { key: 'All', dot: 'var(--teal)' },
  { key: 'Dawntrail', dot: '#c98ee0' },
  { key: 'Endwalker', dot: '#5ea8e0' },
];
