/* Auto-generated by backend/scripts/build-weather.mjs — DO NOT EDIT BY HAND.
   Per-zone Eorzean weather tables: ordered [cumulativeThreshold, weatherName]
   pairs consumed by src/eorzeaWeather.js (chance < threshold ⇒ that weather).
   Source: Garland Tools skywatcher data. */

export const ZONE_WEATHER = {
  "Amh Araeng": [
    [
      45,
      "Fair Skies"
    ],
    [
      60,
      "Clouds"
    ],
    [
      70,
      "Dust Storms"
    ],
    [
      80,
      "Heat Waves"
    ],
    [
      100,
      "Clear Skies"
    ]
  ],
  "Central Shroud": [
    [
      5,
      "Thunder"
    ],
    [
      20,
      "Rain"
    ],
    [
      30,
      "Fog"
    ],
    [
      40,
      "Clouds"
    ],
    [
      55,
      "Fair Skies"
    ],
    [
      85,
      "Clear Skies"
    ],
    [
      100,
      "Fair Skies"
    ]
  ],
  "East Shroud": [
    [
      5,
      "Thunder"
    ],
    [
      20,
      "Rain"
    ],
    [
      30,
      "Fog"
    ],
    [
      40,
      "Clouds"
    ],
    [
      55,
      "Fair Skies"
    ],
    [
      85,
      "Clear Skies"
    ],
    [
      100,
      "Fair Skies"
    ]
  ],
  "Eastern La Noscea": [
    [
      5,
      "Fog"
    ],
    [
      50,
      "Clear Skies"
    ],
    [
      80,
      "Fair Skies"
    ],
    [
      90,
      "Clouds"
    ],
    [
      95,
      "Rain"
    ],
    [
      100,
      "Showers"
    ]
  ],
  "Elpis": [
    [
      25,
      "Clouds"
    ],
    [
      40,
      "Umbral Wind"
    ],
    [
      85,
      "Fair Skies"
    ],
    [
      100,
      "Clear Skies"
    ]
  ],
  "Elysion": [
    [
      15,
      "Apocalypse"
    ],
    [
      85,
      "Fair Skies"
    ],
    [
      100,
      "Umbral Wind"
    ]
  ],
  "Garlemald": [
    [
      45,
      "Snow"
    ],
    [
      50,
      "Thunder"
    ],
    [
      55,
      "Rain"
    ],
    [
      60,
      "Fog"
    ],
    [
      85,
      "Clouds"
    ],
    [
      95,
      "Fair Skies"
    ],
    [
      100,
      "Clear Skies"
    ]
  ],
  "Heritage Found": [
    [
      5,
      "Fair Skies"
    ],
    [
      25,
      "Clouds"
    ],
    [
      40,
      "Fog"
    ],
    [
      45,
      "Rain"
    ],
    [
      50,
      "Thunderstorms"
    ],
    [
      100,
      "Umbral Static"
    ]
  ],
  "Il Mheg": [
    [
      10,
      "Rain"
    ],
    [
      20,
      "Fog"
    ],
    [
      35,
      "Clouds"
    ],
    [
      45,
      "Thunderstorms"
    ],
    [
      60,
      "Clear Skies"
    ],
    [
      100,
      "Fair Skies"
    ]
  ],
  "Kholusia": [
    [
      10,
      "Gales"
    ],
    [
      20,
      "Rain"
    ],
    [
      30,
      "Fog"
    ],
    [
      45,
      "Clouds"
    ],
    [
      85,
      "Fair Skies"
    ],
    [
      100,
      "Clear Skies"
    ]
  ],
  "Kozama'uka": [
    [
      25,
      "Clear Skies"
    ],
    [
      60,
      "Fair Skies"
    ],
    [
      75,
      "Clouds"
    ],
    [
      85,
      "Fog"
    ],
    [
      95,
      "Rain"
    ],
    [
      100,
      "Showers"
    ]
  ],
  "Labyrinthos": [
    [
      15,
      "Clear Skies"
    ],
    [
      60,
      "Fair Skies"
    ],
    [
      85,
      "Clouds"
    ],
    [
      100,
      "Rain"
    ]
  ],
  "Lakeland": [
    [
      20,
      "Clear Skies"
    ],
    [
      60,
      "Fair Skies"
    ],
    [
      75,
      "Clouds"
    ],
    [
      85,
      "Fog"
    ],
    [
      95,
      "Rain"
    ],
    [
      100,
      "Thunderstorms"
    ]
  ],
  "Living Memory": [
    [
      10,
      "Rain"
    ],
    [
      20,
      "Fog"
    ],
    [
      40,
      "Clouds"
    ],
    [
      100,
      "Fair Skies"
    ]
  ],
  "Mare Lamentorum": [
    [
      15,
      "Umbral Wind"
    ],
    [
      30,
      "Astromagnetic Storms"
    ],
    [
      100,
      "Fair Skies"
    ]
  ],
  "North Shroud": [
    [
      5,
      "Fog"
    ],
    [
      10,
      "Showers"
    ],
    [
      25,
      "Rain"
    ],
    [
      30,
      "Fog"
    ],
    [
      40,
      "Clouds"
    ],
    [
      70,
      "Fair Skies"
    ],
    [
      100,
      "Clear Skies"
    ]
  ],
  "Old Sharlayan": [
    [
      10,
      "Clear Skies"
    ],
    [
      50,
      "Fair Skies"
    ],
    [
      70,
      "Clouds"
    ],
    [
      85,
      "Fog"
    ],
    [
      100,
      "Snow"
    ]
  ],
  "Radz-at-Han": [
    [
      10,
      "Fog"
    ],
    [
      25,
      "Rain"
    ],
    [
      40,
      "Clear Skies"
    ],
    [
      80,
      "Fair Skies"
    ],
    [
      100,
      "Clouds"
    ]
  ],
  "Shaaloani": [
    [
      5,
      "Clear Skies"
    ],
    [
      50,
      "Fair Skies"
    ],
    [
      70,
      "Clouds"
    ],
    [
      85,
      "Dust Storms"
    ],
    [
      100,
      "Gales"
    ]
  ],
  "Solution Nine": [
    [
      100,
      "Fair Skies"
    ]
  ],
  "South Shroud": [
    [
      5,
      "Fog"
    ],
    [
      10,
      "Thunderstorms"
    ],
    [
      25,
      "Thunder"
    ],
    [
      30,
      "Fog"
    ],
    [
      40,
      "Clouds"
    ],
    [
      70,
      "Fair Skies"
    ],
    [
      100,
      "Clear Skies"
    ]
  ],
  "Thavnair": [
    [
      10,
      "Fog"
    ],
    [
      20,
      "Rain"
    ],
    [
      25,
      "Showers"
    ],
    [
      40,
      "Clear Skies"
    ],
    [
      80,
      "Fair Skies"
    ],
    [
      100,
      "Clouds"
    ]
  ],
  "The Dravanian Forelands": [
    [
      10,
      "Clouds"
    ],
    [
      20,
      "Fog"
    ],
    [
      30,
      "Thunder"
    ],
    [
      40,
      "Dust Storms"
    ],
    [
      70,
      "Clear Skies"
    ],
    [
      100,
      "Fair Skies"
    ]
  ],
  "The Dravanian Hinterlands": [
    [
      10,
      "Clouds"
    ],
    [
      20,
      "Fog"
    ],
    [
      30,
      "Rain"
    ],
    [
      40,
      "Showers"
    ],
    [
      70,
      "Clear Skies"
    ],
    [
      100,
      "Fair Skies"
    ]
  ],
  "The Rak'tika Greatwood": [
    [
      10,
      "Fog"
    ],
    [
      20,
      "Rain"
    ],
    [
      30,
      "Umbral Wind"
    ],
    [
      45,
      "Clear Skies"
    ],
    [
      85,
      "Fair Skies"
    ],
    [
      100,
      "Clouds"
    ]
  ],
  "The Ruby Sea": [
    [
      10,
      "Thunder"
    ],
    [
      20,
      "Wind"
    ],
    [
      35,
      "Clouds"
    ],
    [
      75,
      "Fair Skies"
    ],
    [
      100,
      "Clear Skies"
    ]
  ],
  "The Sea of Clouds": [
    [
      30,
      "Clear Skies"
    ],
    [
      60,
      "Fair Skies"
    ],
    [
      70,
      "Clouds"
    ],
    [
      80,
      "Fog"
    ],
    [
      90,
      "Wind"
    ],
    [
      100,
      "Umbral Wind"
    ]
  ],
  "Tuliyollal": [
    [
      40,
      "Clear Skies"
    ],
    [
      80,
      "Fair Skies"
    ],
    [
      85,
      "Clouds"
    ],
    [
      95,
      "Fog"
    ],
    [
      100,
      "Rain"
    ]
  ],
  "Ultima Thule": [
    [
      15,
      "Apocalypse"
    ],
    [
      85,
      "Fair Skies"
    ],
    [
      100,
      "Umbral Wind"
    ]
  ],
  "Urqopacha": [
    [
      20,
      "Clear Skies"
    ],
    [
      50,
      "Fair Skies"
    ],
    [
      70,
      "Clouds"
    ],
    [
      80,
      "Fog"
    ],
    [
      90,
      "Wind"
    ],
    [
      100,
      "Snow"
    ]
  ],
  "Western Thanalan": [
    [
      40,
      "Clear Skies"
    ],
    [
      60,
      "Fair Skies"
    ],
    [
      85,
      "Clouds"
    ],
    [
      95,
      "Fog"
    ],
    [
      100,
      "Rain"
    ]
  ],
  "Yak T'el": [
    [
      15,
      "Clear Skies"
    ],
    [
      55,
      "Fair Skies"
    ],
    [
      70,
      "Clouds"
    ],
    [
      85,
      "Fog"
    ],
    [
      100,
      "Rain"
    ]
  ]
}
